; Galaga (Namco rev. B) -- SOUND CPU (gg1_7b.2c)
; GENERATED by tools/gen-listing.mjs from galaga.rom. Do not edit.
; Names and comments: G. Neidermeier galagao source (reference/neiderm), aligned
; against rev. B. "[rev B]" marks bytes with no counterpart in that source.
; 2982/2992 source items placed.


;; gg1-7.s
;;  gg1-7.2c, CPU 'sub2' (Z80)
;; RST_00()
;;  Description:
;; IN:
;;  ...
;; OUT:
;;  ...
0000: 31 00 9B                ld   sp,$9B00         ; {ld sp,#_stack_cpu_sub2 + 0x20}
0003: C3 85 00                jp   $0085            ; -> RESET  {jp RESET}
0006: FF FF                   .db   $FF,$FF  ; [rev B]

;; RST_08()
;;  Description:
;; IN:
;;  ...
;; OUT:
;;  ...
0008: 87                      add  a,a              
0009: 30 05                   jr   nc,$0010         ; -> _RST_10  {jr nc,_RST_10}
000B: 24                      inc  h                
000C: 18 02                   jr   $0010            ; -> _RST_10  {jr _RST_10}
000E: FF FF                   .db   $FF,$FF  ; [rev B]

;; RST_10()
;;  Description:
;;   HL = HL + A
;; IN:
;; OUT:
;;  ...
_RST_10:
0010: 85                      add  a,l              
0011: 6F                      ld   l,a              
0012: D0                      ret  nc               
0013: 24                      inc  h                
0014: C9                      ret                   
0015: FF FF FF                .db   $FF,$FF,$FF  ; [rev B]

;; RST_18()
;;  Description:
;;   memset((HL), A, B)
;; IN:
;;   HL: pointer
;;   A: fill character
;;   B: count
;; OUT:
;;  ...
_RST_18:
0018: 77                      ld   (hl),a           
0019: 23                      inc  hl               
001A: 10 FC                   djnz $0018            ; -> _RST_18  {djnz _RST_18}
001C: C9                      ret                   
001D: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0025: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
002D: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0035: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
003D: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0045: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
004D: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0055: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
005D: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0065: FF F5 3A 8C 9A A7 28 03 .db   $FF,$F5,$3A,$8C,$9A,$A7,$28,$03  ; [rev B]
006D: F1 ED 45 3E 01 32 22 68 .db   $F1,$ED,$45,$3E,$01,$32,$22,$68  ; [rev B]
0075: 32 8C 9A AF 32 22 68 CD .db   $32,$8C,$9A,$AF,$32,$22,$68,$CD  ; [rev B]
007D: BB 00 AF 32 8C 9A F1    .db   $BB,$00,$AF,$32,$8C,$9A,$F1  ; [rev B]
0084: C9                      ret                   

;; RESET
;;  Description:
;;   entry point from RST 00
;;   Tests the ROM space (length $1000)
;; IN:
;;  ...
;; OUT:
;;  ...
RESET:   ; galagao $0073
0085: 3E 01                   ld   a,$01            
0087: 32 22 68                ld   ($6822),a        ; {ld (_sfr_6822),a} 1 ...cpu #2 nmi acknowledge/enable
008A: 11 01 91                ld   de,$9101         ; {ld de,#ds_rom_test_status + 0x01} pause/resume flag

;; wait for master CPU to acknowledge/resume (0)
l_007B:   ; galagao $007B
008D: 1A                      ld   a,(de)           
008E: A7                      and  a                
008F: 20 FC                   jr   nz,$008D         ; -> l_007B

;; compute ROM checksum
0091: 67                      ld   h,a              
0092: 6F                      ld   l,a              
0093: 01 10 00                ld   bc,$0010         ; Sets B as inner loop count ($100) and C as outer ($10)
l_0084:   ; galagao $0084
0096: 86                      add  a,(hl)           
0097: 23                      inc  hl               
0098: 10 FC                   djnz $0096            ; -> l_0084
009A: 0D                      dec  c                
009B: 20 F9                   jr   nz,$0096         ; -> l_0084
009D: FE FF                   cp   $FF              ; {cp #0xFF}
009F: 28 02                   jr   z,$00A3          ; -> l_0091
00A1: 3E 21                   ld   a,$21            ; [rev B]
l_0091:   ; galagao $0091
00A3: 12                      ld   (de),a           ; copy checksum result to the global variable

;; wait for master to acknowledge/resume (0)
l_0092:   ; galagao $0092
00A4: 1A                      ld   a,(de)           
00A5: A7                      and  a                
00A6: 20 FC                   jr   nz,$00A4         ; -> l_0092
00A8: AF                      xor  a                
00A9: 32 22 68                ld   ($6822),a        ; {ld (_sfr_6822),a} 0 ...cpu #2 nmi acknowledge/enable (Z80_NMI_INT)

;; clear all registers
00AC: 21 00 9A                ld   hl,$9A00         ; [b_9A00] memset(b_9A00, 0, $0100)
00AF: 36 00                   ld   (hl),$00         
00B1: 11 01 9A                ld   de,$9A01         ; memset(b_9A00, 0, $0100)
00B4: 01 FF 00                ld   bc,$00FF         
00B7: ED B0                   ldir                  
l_00A7:   ; galagao $00A7
00B9: 18 FE                   jr   $00B9            ; -> l_00A7  loop forever

;; c_nmi_proc()
;;  Description:
;;    Handler for NMI
;; IN:
;;  ...
;; OUT:
;;  ...
c_nmi_proc:   ; galagao $00A9
00BB: 3A B8 9A                ld   a,($9AB8)        ; [$9AB8: 18: 1 ... skips CPUsub2 NMI if set (test variable?)] sound-fx count/enable registers, unused?
00BE: A7                      and  a                
00BF: C2 AB 06                jp   nz,$06AB         ; -> l_067A_reset_sfrs  {jp nz,l_067A_reset_sfrs} doesn't appear that it is ever called

;; memset( b_freq_vol_sfr_bufr, 0, $10 )
00C2: 21 60 9A                ld   hl,$9A60         ; [b_9A60: $10 bytes copied to 6810 (frequency & volume SFRs)] clear frequency and volume SFRs
00C5: 36 00                   ld   (hl),$00         
00C7: 11 61 9A                ld   de,$9A61         
00CA: 01 0F 00                ld   bc,$000F         
00CD: ED B0                   ldir                  

;; if ( sound_mgr_reset )  ...
00CF: 3A B7 9A                ld   a,($9AB7)        ; [$9AB7: 17: 0 ... enable CPU-sub2 process] 0 ... enable sound mgr process
00D2: A7                      and  a                
00D3: C2 4C 03                jp   nz,$034C         ; -> l_033D_clear_all  {jp nz,l_033D_clear_all}

;; ... then ...
;; credit-in sound is triggered for all credits counted
;; if ( 0 != snd_add_credit_cnt )
00D6: 3A 79 9A                ld   a,($9A79)        ; [$9A79: 09: global copy of count of additional credits-in since last update for triggering coiin-in sound] count of credits-in since last update
00D9: A7                      and  a                
00DA: 28 09                   jr   z,$00E5          ; -> l_00D3

;; then ...
;; _fx[$08] += snd_add_credit_cnt
00DC: 21 A8 9A                ld   hl,$9AA8         ; [$9AA8: 08:  count/enable register ... coin sound] += b_9A70[9] ... sound-fx count/enable registers, credit-in sound
00DF: 86                      add  a,(hl)           
00E0: 77                      ld   (hl),a           

;; snd_add_credit_cnt = 0
00E1: AF                      xor  a                
00E2: 32 79 9A                ld   ($9A79),a        ; [$9A79: 09: global copy of count of additional credits-in since last update for triggering coiin-in sound] 0 ... additional credit-in count

;; ...
;; if ( 0 != register )  ...  count/enable register
l_00D3:   ; galagao $00D3
00E5: 3A A0 9A                ld   a,($9AA0)        ; [ds_9AA0: label for pointer+index operations] sound-fx count/enable registers, pulsing formation sound effect
00E8: A7                      and  a                
00E9: 28 6F                   jr   z,$015A          ; -> l_0148

;; ... then ...
00EB: 3A 11 92                ld   a,($9211)        ; {ld a,(ds_9200_glbls + 0x11)} formatn_mv_signage ... cp with cpu2<b_9A80 + 0x00>
00EE: 21 80 9A                ld   hl,$9A80         ; [b_9A80: 00:]
00F1: BE                      cp   (hl)             
00F2: 28 20                   jr   z,$0114          ; -> l_0102
00F4: 32 80 9A                ld   ($9A80),a        ; [b_9A80: 00:] = ds_9200_glbls [0x11] ... formatn_mv_signage
00F7: 3C                      inc  a                
00F8: 28 0C                   jr   z,$0106          ; -> l_00F4

;; expanding formation
00FA: 21 F4 06                ld   hl,$06F4         
00FD: 22 82 9A                ld   ($9A82),hl       ; [$9A82: 02:] ptmp = &d_06C3[0]
0100: AF                      xor  a                
0101: 32 00 9A                ld   ($9A00),a        ; [b_9A00] 0 .. sound_fx_status
0104: 18 09                   jr   $010F            ; -> l_00FD

;; contracting formation
;; A == 0
l_00F4:   ; galagao $00F4
0106: 21 04 07                ld   hl,$0704         ; offset 8 words
0109: 22 82 9A                ld   ($9A82),hl       ; [$9A82: 02:] ptmp = &d_06D3[0]
010C: 32 00 9A                ld   ($9A00),a        ; [b_9A00] 0 ... sound_fx_status

;; A == 0
l_00FD:   ; galagao $00FD
010F: 32 81 9A                ld   ($9A81),a        ; [$9A81: 01:] A == 0  or  A != 0 (only gets updated when b_9A80_00 == formatn_mv_signage
0112: 18 12                   jr   $0126            ; -> l_0114
l_0102:   ; galagao $0102
0114: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[0]++ (check for limit of 34)
0117: 34                      inc  (hl)             
0118: 7E                      ld   a,(hl)           
0119: FE 22                   cp   $22              
011B: 20 1E                   jr   nz,$013B         ; -> l_0129
011D: 36 00                   ld   (hl),$00         ; sound_fx_status[0] = 0
011F: 3A 81 9A                ld   a,($9A81)        ; [$9A81: 01:] b_9A80[1]++
0122: 3C                      inc  a                
0123: 32 81 9A                ld   ($9A81),a        ; [$9A81: 01:] b_9A80[1]++
l_0114:   ; galagao $0114
0126: 2A 82 9A                ld   hl,($9A82)       ; [$9A82: 02:] ptmp ... d_06C3 or d_06D3
0129: CF                      rst  $08              ; HL += 2A
012A: 5E                      ld   e,(hl)           
012B: 23                      inc  hl               
012C: 56                      ld   d,(hl)           
012D: ED 53 84 9A             ld   ($9A84),de       ; [$9A84: 04:]
0131: 3E 1F                   ld   a,$1F            ; $20 - $01 (1-byte increment to next word already done)
0133: D7                      rst  $10              ; HL += A
0134: 5E                      ld   e,(hl)           
0135: 23                      inc  hl               
0136: 56                      ld   d,(hl)           
0137: ED 53 86 9A             ld   ($9A86),de       ; [$9A86: 06:]
l_0129:   ; galagao $0129
013B: 2A 86 9A                ld   hl,($9A86)       ; [$9A86: 06:] b_9A80[6] += b_9A80[4]
013E: ED 5B 84 9A             ld   de,($9A84)       ; [$9A84: 04:]
0142: 19                      add  hl,de            
0143: 22 86 9A                ld   ($9A86),hl       ; [$9A86: 06:]
0146: 7C                      ld   a,h              
0147: 32 61 9A                ld   ($9A61),a        ; freq 0
014A: 0F                      rrca                  
014B: 0F                      rrca                  
014C: 0F                      rrca                  
014D: 0F                      rrca                  
014E: 32 62 9A                ld   ($9A62),a        
0151: 3E 0A                   ld   a,$0A            
0153: 32 65 9A                ld   ($9A65),a        ; $0A ... voice 0 volume
0156: AF                      xor  a                
0157: 32 70 9A                ld   ($9A70),a        ; [b_9A70: 00: voice 0 wave select] 0 ... voice 0 wave select

;; bug dive attack sound
l_0148:   ; galagao $0148
015A: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $13 ... bug dive attack sound
015D: 36 13                   ld   (hl),$13         
015F: 3A B3 9A                ld   a,($9AB3)        ; [$9AB3: 13:] sound-fx count/enable registers, bug dive attack sound
0162: A7                      and  a                
0163: 28 09                   jr   z,$016E          ; -> l_015C
0165: AF                      xor  a                
0166: 32 B3 9A                ld   ($9AB3),a        ; [$9AB3: 13:] 0 ... sound-fx count/enable registers, bug dive attack sound
0169: CD 03 04                call $0403            ; -> c_03F4  initialize the sound
016C: 18 09                   jr   $0177            ; -> l_0165
l_015C:   ; galagao $015C
016E: 3A D3 9A                ld   a,($9AD3)        ; check if sound is active
0171: A7                      and  a                
0172: 28 03                   jr   z,$0177          ; -> l_0165
0174: CD 59 04                call $0459            ; -> c_044A  update the sound

;; shot sound
l_0165:   ; galagao $0165
0177: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $0F
017A: 36 0F                   ld   (hl),$0F         
017C: 3A AF 9A                ld   a,($9AAF)        ; [$9AAF: 0F:] sound-fx count/enable registers, shot sound
017F: A7                      and  a                
0180: 28 09                   jr   z,$018B          ; -> l_0179
0182: AF                      xor  a                
0183: 32 AF 9A                ld   ($9AAF),a        ; [$9AAF: 0F:] 0 ... sound-fx count/enable registers, shot sound
0186: CD 03 04                call $0403            ; -> c_03F4
0189: 18 09                   jr   $0194            ; -> l_0182
l_0179:   ; galagao $0179
018B: 3A CF 9A                ld   a,($9ACF)        
018E: A7                      and  a                
018F: 28 03                   jr   z,$0194          ; -> l_0182
0191: CD 59 04                call $0459            ; -> c_044A

;; yellow bug hit sound
l_0182:   ; galagao $0182
0194: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $03
0197: 36 03                   ld   (hl),$03         
0199: 3A A3 9A                ld   a,($9AA3)        ; [$9AA3: 03:] sound-fx count/enable registers, yellow bug hit sound
019C: A7                      and  a                
019D: 28 09                   jr   z,$01A8          ; -> l_0196
019F: AF                      xor  a                
01A0: 32 A3 9A                ld   ($9AA3),a        ; [$9AA3: 03:] 0 ... sound-fx count/enable registers, yellow bug hit sound
01A3: CD 03 04                call $0403            ; -> c_03F4
01A6: 18 09                   jr   $01B1            ; -> l_019F
l_0196:   ; galagao $0196
01A8: 3A C3 9A                ld   a,($9AC3)        
01AB: A7                      and  a                
01AC: 28 03                   jr   z,$01B1          ; -> l_019F
01AE: CD 59 04                call $0459            ; -> c_044A

;; red bug hit sound
l_019F:   ; galagao $019F
01B1: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $02
01B4: 36 02                   ld   (hl),$02         
01B6: 3A A2 9A                ld   a,($9AA2)        ; [$9AA2: 02:] sound-fx count/enable registers, red bug hit sound
01B9: A7                      and  a                
01BA: 28 09                   jr   z,$01C5          ; -> l_01B3
01BC: AF                      xor  a                
01BD: 32 A2 9A                ld   ($9AA2),a        ; [$9AA2: 02:] 0 ... sound-fx count/enable registers, red bug hit sound
01C0: CD 03 04                call $0403            ; -> c_03F4
01C3: 18 09                   jr   $01CE            ; -> l_01BC
l_01B3:   ; galagao $01B3
01C5: 3A C2 9A                ld   a,($9AC2)        
01C8: A7                      and  a                
01C9: 28 03                   jr   z,$01CE          ; -> l_01BC
01CB: CD 59 04                call $0459            ; -> c_044A

;; hit_green_boss
l_01BC:   ; galagao $01BC
01CE: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $04
01D1: 36 04                   ld   (hl),$04         
01D3: 3A A4 9A                ld   a,($9AA4)        ; [$9AA4: 04:] sound-fx count/enable registers, hit_green_boss
01D6: A7                      and  a                
01D7: 28 09                   jr   z,$01E2          ; -> l_01D0
01D9: AF                      xor  a                
01DA: 32 A4 9A                ld   ($9AA4),a        ; [$9AA4: 04:] 0 ... sound-fx count/enable registers, hit_green_boss
01DD: CD 03 04                call $0403            ; -> c_03F4
01E0: 18 09                   jr   $01EB            ; -> l_01D9
l_01D0:   ; galagao $01D0
01E2: 3A C4 9A                ld   a,($9AC4)        
01E5: A7                      and  a                
01E6: 28 03                   jr   z,$01EB          ; -> l_01D9
01E8: CD 59 04                call $0459            ; -> c_044A

;; hit_blue_boss
l_01D9:   ; galagao $01D9
01EB: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $01
01EE: 36 01                   ld   (hl),$01         
01F0: 3A A1 9A                ld   a,($9AA1)        ; [$9AA1: 01:  blue-boss hit sound] sound-fx count/enable registers, blue-boss hit sound
01F3: A7                      and  a                
01F4: 28 09                   jr   z,$01FF          ; -> l_01ED
01F6: AF                      xor  a                
01F7: 32 A1 9A                ld   ($9AA1),a        ; [$9AA1: 01:  blue-boss hit sound] 0 ... sound-fx count/enable registers, blue-boss hit sound
01FA: CD 03 04                call $0403            ; -> c_03F4
01FD: 18 09                   jr   $0208            ; -> l_01F6
l_01ED:   ; galagao $01ED
01FF: 3A C1 9A                ld   a,($9AC1)        
0202: A7                      and  a                
0203: 28 03                   jr   z,$0208          ; -> l_01F6
0205: CD 59 04                call $0459            ; -> c_044A

;; bonus-bee sound
l_01F6:   ; galagao $01F6
0208: 3A B2 9A                ld   a,($9AB2)        ; [$9AB2: 12:] sound-fx count/enable registers, bonus-bee sound
020B: A7                      and  a                
020C: 28 08                   jr   z,$0216          ; -> l_0204
020E: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $12
0211: 36 12                   ld   (hl),$12         
0213: CD B1 04                call $04B1            ; -> c_04A2

;; sound mgr capture beam
;; if ( !_fx[$05] )  {  }  else { goto l_0236 }
l_0204:   ; galagao $0204
0216: 3A A5 9A                ld   a,($9AA5)        ; [$9AA5: 05:  capture beam sound active uno] sound-fx count/enable registers, capture beam active uno
0219: A7                      and  a                
021A: 28 2C                   jr   z,$0248          ; -> l_0236
021C: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $05 ... capture beam
021F: 36 05                   ld   (hl),$05         
0221: CD 84 03                call $0384            ; -> c_0375

;; if ( ++b_9A70[0x0E] >= 6 )  { }  else  { goto l_022E }
0224: 21 7E 9A                ld   hl,$9A7E         ; [$9A7E: 0E: counter, tracks voice 2 volume change ... capture beam]
0227: 34                      inc  (hl)             
0228: 3A 7E 9A                ld   a,($9A7E)        ; [$9A7E: 0E: counter, tracks voice 2 volume change ... capture beam]
022B: FE 06                   cp   $06              
022D: 38 11                   jr   c,$0240          ; -> l_022E
022F: 36 00                   ld   (hl),$00         

;; if ( b_9A70[0x0C] < 4 )  b_9A70[0x0C] = 0x0C  else  b_9A70[0x0C]--
0231: 3A 7C 9A                ld   a,($9A7C)        ; [$9A7C: 0C: voice 2 volume for capture beam]
0234: FE 04                   cp   $04              
0236: 38 03                   jr   c,$023B          ; -> l_0229
0238: 3D                      dec  a                
0239: 18 02                   jr   $023D            ; -> l_022B
l_0229:   ; galagao $0229
023B: 3E 0C                   ld   a,$0C            
l_022B:   ; galagao $022B
023D: 32 7C 9A                ld   ($9A7C),a        ; [$9A7C: 0C: voice 2 volume for capture beam]
l_022E:   ; galagao $022E
0240: 3A 7C 9A                ld   a,($9A7C)        ; [$9A7C: 0C: voice 2 volume for capture beam] ->voice 2 volume
0243: 32 6F 9A                ld   ($9A6F),a        ; voice 2 volume
0246: 18 03                   jr   $024B            ; -> j_0239
l_0236:   ; galagao $0236
0248: 32 C5 9A                ld   ($9AC5),a        ; 0 ... capture beam count/enable uno == 0, so clear the active flag

;; if ( sound_active )  { }  else  _fx[$06] = 0
j_0239:   ; galagao $0239
024B: 3A A6 9A                ld   a,($9AA6)        ; [$9AA6: 06:  capture beam sound active deux] sound-fx count/enable registers, capture beam active deux
024E: A7                      and  a                
024F: 28 24                   jr   z,$0275          ; -> l_0263
0251: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $06
0254: 36 06                   ld   (hl),$06         
0256: CD 84 03                call $0384            ; -> c_0375

;; if ( ++b_9A70[0x0F] == $1C )  b_9A70[0x0F] = 0, b_9A70[0x0D]++
0259: 21 7F 9A                ld   hl,$9A7F         ; [$9A7F: 0F: counter for wave-select (tractor beam)]
025C: 34                      inc  (hl)             
025D: 7E                      ld   a,(hl)           
025E: FE 1C                   cp   $1C              
0260: 20 0B                   jr   nz,$026D         ; -> l_025B
0262: AF                      xor  a                
0263: 32 7F 9A                ld   ($9A7F),a        ; [$9A7F: 0F: counter for wave-select (tractor beam)] 0
0266: 3A 7D 9A                ld   a,($9A7D)        ; [$9A7D: 0D: counter for wave-select (tractor beam)]
0269: 3C                      inc  a                
026A: 32 7D 9A                ld   ($9A7D),a        ; [$9A7D: 0D: counter for wave-select (tractor beam)] ++
l_025B:   ; galagao $025B
026D: 3A 7D 9A                ld   a,($9A7D)        ; [$9A7D: 0D: counter for wave-select (tractor beam)]
0270: 32 70 9A                ld   ($9A70),a        ; [b_9A70: 00: voice 0 wave select] 0 ... voice 2 wave select
0273: 18 03                   jr   $0278            ; -> l_0266
l_0263:   ; galagao $0263
0275: 32 C6 9A                ld   ($9AC6),a        ; 0 ... deactivate capture beam part deux

;; $9 .. $7
l_0266:   ; galagao $0266
0278: 3A A9 9A                ld   a,($9AA9)        ; [$9AA9: 09:  ?] sound-fx count/enable registers
027B: A7                      and  a                
027C: 28 0A                   jr   z,$0288          ; -> l_0276
027E: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $09
0281: 36 09                   ld   (hl),$09         
0283: CD 84 03                call $0384            ; -> c_0375
0286: 18 03                   jr   $028B            ; -> l_0279
l_0276:   ; galagao $0276
0288: 32 C9 9A                ld   ($9AC9),a        ; 0 ... clear the active flag

;; shot your ship!
l_0279:   ; galagao $0279
028B: 3A A7 9A                ld   a,($9AA7)        ; [$9AA7: 07:] sound-fx count/enable registers, shot your ship!
028E: A7                      and  a                
028F: 28 0B                   jr   z,$029C          ; -> l_0287
0291: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $07
0294: 36 07                   ld   (hl),$07         
0296: CD B1 04                call $04B1            ; -> c_04A2
0299: C3 3C 03                jp   $033C            ; -> l_032D  [rev B]

;; "rescued ship" theme
l_0287:   ; galagao $0287
029C: 3A B1 9A                ld   a,($9AB1)        ; [$9AB1: 11:  count/enable register ... rescued ship theme] sound-fx count/enable registers, "rescued ship" theme
029F: A7                      and  a                
02A0: 28 0A                   jr   z,$02AC          ; -> l_0297
02A2: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $11
02A5: 36 11                   ld   (hl),$11         
02A7: CD 84 03                call $0384            ; -> c_0375
02AA: 18 03                   jr   $02AF            ; -> l_029A
l_0297:   ; galagao $0297
02AC: 32 D1 9A                ld   ($9AD1),a        ; clear the active flag

;; challenge stage intro music
l_029A:   ; galagao $029A
02AF: 3A AD 9A                ld   a,($9AAD)        ; [$9AAD: 0D:] sound-fx count/enable registers, start challenge stage music
02B2: A7                      and  a                
02B3: 28 08                   jr   z,$02BD          ; -> l_02A8
02B5: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $0D
02B8: 36 0D                   ld   (hl),$0D         
02BA: CD B1 04                call $04B1            ; -> c_04A2

;; challenge stage default melody
l_02A8:   ; galagao $02A8
02BD: 3A AE 9A                ld   a,($9AAE)        ; [$9AAE: 0R:] sound-fx count/enable registers, challenge stage default melody
02C0: A7                      and  a                
02C1: 28 12                   jr   z,$02D5          ; -> l_02C6  well this seems like a waste of time
02C3: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $0E
02C6: 36 0E                   ld   (hl),$0E         
02C8: CD B1 04                call $04B1            ; -> c_04A2
02CB: 3E 09                   ld   a,$09            
02CD: 32 6A 9A                ld   ($9A6A),a        ; 9 ... voice 1 volume
02D0: 3E 06                   ld   a,$06            
02D2: 32 6F 9A                ld   ($9A6F),a        ; 6 ... voice 2 volume

;; challenge stage perfect melody
l_02C6:   ; galagao $02C6
02D5: 3A B4 9A                ld   a,($9AB4)        ; [$9AB4: 14:] sound-fx count/enable registers, challenge stage perfect melody
02D8: A7                      and  a                
02D9: 28 08                   jr   z,$02E3          ; -> l_02D4
02DB: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $14
02DE: 36 14                   ld   (hl),$14         
02E0: CD B1 04                call $04B1            ; -> c_04A2

;; stage tokens "clicks"
l_02D4:   ; galagao $02D4
02E3: 3A B5 9A                ld   a,($9AB5)        ; [$9AB5: 15: clicks for stage tokens] sound-fx count/enable registers, stage tokens "clicks"
02E6: A7                      and  a                
02E7: 28 08                   jr   z,$02F1          ; -> l_02E2
02E9: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $15
02EC: 36 15                   ld   (hl),$15         
02EE: CD B1 04                call $04B1            ; -> c_04A2

;; new spare ship added
l_02E2:   ; galagao $02E2
02F1: 3A AA 9A                ld   a,($9AAA)        ; [$9AAA: 0A:] sound-fx count/enable registers, new spare ship added
02F4: A7                      and  a                
02F5: 28 08                   jr   z,$02FF          ; -> l_02F0
02F7: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $0A
02FA: 36 0A                   ld   (hl),$0A         
02FC: CD B1 04                call $04B1            ; -> c_04A2

;; start of game theme
l_02F0:   ; galagao $02F0
02FF: 3A AB 9A                ld   a,($9AAB)        ; [$9AAB: 0B:] sound-fx count/enable registers, start of game theme
0302: A7                      and  a                
0303: 28 08                   jr   z,$030D          ; -> l_02FE
0305: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $0B
0308: 36 0B                   ld   (hl),$0B         
030A: CD B1 04                call $04B1            ; -> c_04A2

;; $10
l_02FE:   ; galagao $02FE
030D: 3A B0 9A                ld   a,($9AB0)        ; [$9AB0: 10:] sound-fx count/enable registers, hi-score dialog?
0310: A7                      and  a                
0311: 28 0A                   jr   z,$031D          ; -> l_030E
0313: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $10
0316: 36 10                   ld   (hl),$10         
0318: CD 84 03                call $0384            ; -> c_0375
031B: 18 03                   jr   $0320            ; -> l_0311
l_030E:   ; galagao $030E
031D: 32 D0 9A                ld   ($9AD0),a        ; clear the active flag

;; hi-score dialog?
l_0311:   ; galagao $0311
0320: 3A AC 9A                ld   a,($9AAC)        ; [$9AAC: 0C:] sound-fx count/enable registers, hi-score dialog?
0323: A7                      and  a                
0324: 28 08                   jr   z,$032E          ; -> l_031F
0326: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $0C
0329: 36 0C                   ld   (hl),$0C         
032B: CD B1 04                call $04B1            ; -> c_04A2

;; hi-score dialog?
l_031F:   ; galagao $031F
032E: 3A B6 9A                ld   a,($9AB6)        ; [$9AB6: 16: sound mgr, hi-score dialog] sound-fx count/enable registers, hi-score dialog?
0331: A7                      and  a                
0332: 28 08                   jr   z,$033C          ; -> l_032D
0334: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] $16
0337: 36 16                   ld   (hl),$16         
0339: CD B1 04                call $04B1            ; -> c_04A2

;; coin sound
l_032D:   ; galagao $032D
033C: 3A A8 9A                ld   a,($9AA8)        ; [$9AA8: 08:  count/enable register ... coin sound] sound-fx count/enable registers, coin sound
033F: A7                      and  a                
0340: 28 08                   jr   z,$034A          ; -> l_033B
0342: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] actv_snd_idx = $08
0345: 36 08                   ld   (hl),$08         ; actv_snd_idx
0347: CD B1 04                call $04B1            ; -> c_04A2  _fx[$08] will be decremented
l_033B:   ; galagao $033B
034A: 18 1A                   jr   $0366            ; -> j_0357_set_SFRs  {jr j_0357_set_SFRs}

;; memset( snd_cnt_enable, 0, $16 ) .. don't clear [$16], [$17], [$18]
l_033D_clear_all:   ; galagao $033D
034C: 21 A0 9A                ld   hl,$9AA0         ; [ds_9AA0: label for pointer+index operations] sound-fx count/enable registers ... $16 bytes 0
034F: 36 00                   ld   (hl),$00         
0351: 11 A1 9A                ld   de,$9AA1         ; [$9AA1: 01:  blue-boss hit sound] sound-fx count/enable registers ... $16 bytes 0
0354: 01 15 00                ld   bc,$0015         
0357: ED B0                   ldir                  

;; memset( snd_active_flag, 0, $17 ) ...  [$16] should be highest one used
0359: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] $17 bytes 0
035C: 36 00                   ld   (hl),$00         
035E: 11 C1 9A                ld   de,$9AC1         
0361: 01 16 00                ld   bc,$0016         
0364: ED B0                   ldir                  
j_0357_set_SFRs:   ; galagao $0357
0366: 21 60 9A                ld   hl,$9A60         ; [b_9A60: $10 bytes copied to 6810 (frequency & volume SFRs)] memcpy(&sfr_6810[0], buf, $10)
0369: 11 10 68                ld   de,$6810         ; {ld de,#_sfr_6810} base pointer to frequency and volume SFRs
036C: 01 10 00                ld   bc,$0010         
036F: ED B0                   ldir                  

;; set the sound voice waveforms
0371: 3A 70 9A                ld   a,($9A70)        ; [b_9A70: 00: voice 0 wave select]
0374: 32 05 68                ld   ($6805),a        ; {ld (_sfr_6805),a} voice 0 wave
0377: 3A 71 9A                ld   a,($9A71)        
037A: 32 0A 68                ld   ($680A),a        ; {ld (_sfr_680A),a} voice 1 wave
037D: 3A 72 9A                ld   a,($9A72)        
0380: 32 0F 68                ld   ($680F),a        ; {ld (_sfr_680F),a} voice 2 wave
0383: C9                      ret                   

;; c_0375()
;;  Description:
;; IN:
;;  ...
;; OUT:
;;  ...
c_0375:   ; galagao $0375
0384: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] d_0703[ actv_snd_idx * 3 ]
0387: 7E                      ld   a,(hl)           
0388: 87                      add  a,a              
0389: 86                      add  a,(hl)           
038A: 21 34 07                ld   hl,$0734         ; {ld hl,#d_0703_snd_parms}
038D: D7                      rst  $10              ; HL += A
038E: 11 75 9A                ld   de,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] memcpy( snd_parms_set, d_0703[ actv_snd_idx * 3 ], 3 )
0391: 01 03 00                ld   bc,$0003         
0394: ED B0                   ldir                  

;; if challenge stage default melody
0396: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] if ( actv_snd_idx == $0E ) ...
0399: FE 0E                   cp   $0E              
039B: 20 18                   jr   nz,$03B5         ; -> l_03A6

;; if 0 == data_index
039D: 3A 4C 9A                ld   a,($9A4C)        
03A0: A7                      and  a                
03A1: 28 0D                   jr   z,$03B0          ; -> l_03A1

;; else if 1 == data_index
03A3: 3D                      dec  a                
03A4: 28 06                   jr   z,$03AC          ; -> l_039D

;; or if
03A6: 3A 4D 9A                ld   a,($9A4D)        
03A9: A7                      and  a                
03AA: 20 09                   jr   nz,$03B5         ; -> l_03A6
l_039D:   ; galagao $039D
03AC: 3E 02                   ld   a,$02            
03AE: 18 02                   jr   $03B2            ; -> l_03A3
l_03A1:   ; galagao $03A1
03B0: 3E 01                   ld   a,$01            
l_03A3:   ; galagao $03A3
03B2: 32 76 9A                ld   ($9A76),a        ; 1 or 2 .. count: number of data pairs

;; now we are checking active flags for some reason,,,,
l_03A6:   ; galagao $03A6
03B5: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] if ( 0 == b_9AC0[ actv_snd_idx ] )  b_9AC0[ actv_snd_idx ] = 1
03B8: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] b_9AC0[ actv_snd_idx ]
03BB: 85                      add  a,l              
03BC: 6F                      ld   l,a              
03BD: 7E                      ld   a,(hl)           
03BE: A7                      and  a                
03BF: 20 1B                   jr   nz,$03DC         ; -> j_03CD
03C1: 34                      inc  (hl)             
03C2: 21 76 9A                ld   hl,$9A76         ; snd_parms_set.count
03C5: 46                      ld   b,(hl)           

;; memset( &snd_fx_dat_idx[ snd_parms_set.idx ], 0, snd_parms_set.count )
03C6: 48                      ld   c,b              
03C7: 21 30 9A                ld   hl,$9A30         ; [b_9A30] snd_fx_dat_idx[ snd_parms_set.idx ]
03CA: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
03CD: 85                      add  a,l              
03CE: 6F                      ld   l,a              
03CF: AF                      xor  a                
03D0: DF                      rst  $18              ; memset((HL), A=fill, B=ct)

;; memset( &sound_fx_status[ snd_parms_set.idx ], 0, snd_parms_set.count )
03D1: 41                      ld   b,c              
03D2: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ]
03D5: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
03D8: 85                      add  a,l              
03D9: 6F                      ld   l,a              
03DA: AF                      xor  a                
03DB: DF                      rst  $18              ; memset((HL), A=fill, B=ct)
j_03CD:   ; galagao $03CD
l_03CD_while:   ; galagao $03CD
03DC: CD 81 05                call $0581            ; -> c_0550

;; while ( snd_parms_set.count > 0 ) ...
03DF: 21 76 9A                ld   hl,$9A76         ; if ( snd_parms_set.count-- > 0 ) ...
03E2: 35                      dec  (hl)             
03E3: 28 0A                   jr   z,$03EF          ; -> l_03E0
03E5: 21 75 9A                ld   hl,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx++
03E8: 34                      inc  (hl)             
03E9: 21 77 9A                ld   hl,$9A77         ; voice_select++
03EC: 34                      inc  (hl)             
03ED: 18 ED                   jr   $03DC            ; -> j_03CD  {jr l_03CD_while}
l_03E0:   ; galagao $03E0
03EF: 3A 78 9A                ld   a,($9A78)        ; [$9A78: 08:] ret z
03F2: A7                      and  a                
03F3: C8                      ret  z                
03F4: AF                      xor  a                
03F5: 32 78 9A                ld   ($9A78),a        ; [$9A78: 08:] 0

;; clear the sound_active flag for this one
03F8: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] b_9AC0[ actv_snd_idx ] = 0
03FB: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] b_9AC0[ actv_snd_idx ]
03FE: 85                      add  a,l              
03FF: 6F                      ld   l,a              
0400: 36 00                   ld   (hl),$00         

;; exactly the same as c_04A2 until here
0402: C9                      ret                   

;; end 'call _0375'
;; c_03F4()
;;  Description:
;;   Initialize a sound effect. After this one is called once, then c_044A is
;;   called to update the sound on subsequent frame updates.
;; IN:
;;   b_9A70[4]: index of sound to play
;; OUT:
;;  ...
;; on this one we increment the Active flag
c_03F4:   ; galagao $03F4
0403: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] b_9AC0[ actv_snd_idx ]++
0406: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] b_9AC0[ actv_snd_idx ]
0409: 85                      add  a,l              
040A: 6F                      ld   l,a              
040B: 34                      inc  (hl)             

;; same as c_04A2 here
040C: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] d_0703[ actv_snd_idx * 3 ]
040F: 7E                      ld   a,(hl)           
0410: 87                      add  a,a              
0411: 86                      add  a,(hl)           
0412: 21 34 07                ld   hl,$0734         ; {ld hl,#d_0703_snd_parms}
0415: D7                      rst  $10              ; HL += A
0416: 11 75 9A                ld   de,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] memcpy( snd_parms_set, d_0703[ actv_snd_idx * 3 ], 3 )
0419: 01 03 00                ld   bc,$0003         
041C: ED B0                   ldir                  

;; if challenge stage default melody
041E: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] if (actv_snd_idx == $0E) ...
0421: FE 0E                   cp   $0E              
0423: 20 18                   jr   nz,$043D         ; -> l_042E

;; if 0 == data_index
0425: 3A 4C 9A                ld   a,($9A4C)        ; data_index, SOUND 09
0428: A7                      and  a                
0429: 28 0D                   jr   z,$0438          ; -> l_0429

;; else if 1 == data_index
042B: 3D                      dec  a                
042C: 28 06                   jr   z,$0434          ; -> l_0425

;; or if
042E: 3A 4D 9A                ld   a,($9A4D)        ; SOUND 09
0431: A7                      and  a                
0432: 20 09                   jr   nz,$043D         ; -> l_042E
l_0425:   ; galagao $0425
0434: 3E 02                   ld   a,$02            
0436: 18 02                   jr   $043A            ; -> l_042B
l_0429:   ; galagao $0429
0438: 3E 01                   ld   a,$01            
l_042B:   ; galagao $042B
043A: 32 76 9A                ld   ($9A76),a        ; snd_parms_set.count = 1

;; here we don't check the flags...
l_042E:   ; galagao $042E
043D: 21 76 9A                ld   hl,$9A76         ; snd_parms_set.count
0440: 46                      ld   b,(hl)           

;; memset( &snd_fx_dat_idx[ snd_parms_set.idx ], 0, snd_parms_set.count )
0441: 48                      ld   c,b              
0442: 21 30 9A                ld   hl,$9A30         ; [b_9A30] snd_fx_dat_idx[ snd_parms_set.idx ]
0445: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0448: 85                      add  a,l              
0449: 6F                      ld   l,a              
044A: AF                      xor  a                
044B: DF                      rst  $18              ; memset((HL), A=fill, B=ct)

;; memset( &sound_fx_status[ snd_parms_set.idx ], 0, snd_parms_set.count )
044C: 41                      ld   b,c              
044D: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ]
0450: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0453: 85                      add  a,l              
0454: 6F                      ld   l,a              
0455: AF                      xor  a                
0456: DF                      rst  $18              ; memset((HL), A=fill, B=ct)

;; here is where c_0550 is called....
0457: 18 31                   jr   $048A            ; -> j_047B

;; c_044A()
;;  Description:
;;   After c_03F4 is called once to initialize the sound, then on subsequent
;;   frame updates this one is called.
;; IN:
;;  ...
;; OUT:
;;  ...
c_044A:   ; galagao $044A
0459: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] d_0703[ actv_snd_idx * 3 ]
045C: 7E                      ld   a,(hl)           
045D: 87                      add  a,a              
045E: 86                      add  a,(hl)           
045F: 21 34 07                ld   hl,$0734         ; {ld hl,#d_0703_snd_parms}
0462: D7                      rst  $10              ; HL += A
0463: 11 75 9A                ld   de,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] memcpy( snd_parms_set, d_0703[ actv_snd_idx * 3 ], 3 )
0466: 01 03 00                ld   bc,$0003         
0469: ED B0                   ldir                  

;; if challenge stage default melody
046B: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] if (actv_snd_idx == $0E) ...
046E: FE 0E                   cp   $0E              
0470: 20 18                   jr   nz,$048A         ; -> j_047B

;; if 0 == data_index
0472: 3A 4C 9A                ld   a,($9A4C)        
0475: A7                      and  a                
0476: 28 0D                   jr   z,$0485          ; -> l_0476

;; else if 1 == data_index
0478: 3D                      dec  a                
0479: 28 06                   jr   z,$0481          ; -> l_0472

;; or if
047B: 3A 4D 9A                ld   a,($9A4D)        
047E: A7                      and  a                
047F: 20 09                   jr   nz,$048A         ; -> j_047B
l_0472:   ; galagao $0472
0481: 3E 02                   ld   a,$02            
0483: 18 02                   jr   $0487            ; -> l_0478
l_0476:   ; galagao $0476
0485: 3E 01                   ld   a,$01            
l_0478:   ; galagao $0478
0487: 32 76 9A                ld   ($9A76),a        ; snd_parms_set.count

;; doesn't do the other stuff here here....
j_047B:   ; galagao $047B
l_047B:   ; galagao $047B
048A: CD 81 05                call $0581            ; -> c_0550
048D: 21 76 9A                ld   hl,$9A76         ; if ( snd_parms_set.count-- > 0 ) ...
0490: 35                      dec  (hl)             
0491: 28 0A                   jr   z,$049D          ; -> l_048E
0493: 21 75 9A                ld   hl,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx++
0496: 34                      inc  (hl)             
0497: 21 77 9A                ld   hl,$9A77         ; voice_select++
049A: 34                      inc  (hl)             
049B: 18 ED                   jr   $048A            ; -> j_047B
l_048E:   ; galagao $048E
049D: 3A 78 9A                ld   a,($9A78)        ; [$9A78: 08:] ret z
04A0: A7                      and  a                
04A1: C8                      ret  z                
04A2: AF                      xor  a                
04A3: 32 78 9A                ld   ($9A78),a        ; [$9A78: 08:] 0

;; clear the sound_active flag for this one
04A6: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] b_9AC0[ actv_snd_idx ] = 0
04A9: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] b_9AC0[ actv_snd_idx ]
04AC: 85                      add  a,l              
04AD: 6F                      ld   l,a              
04AE: 36 00                   ld   (hl),$00         
04B0: C9                      ret                   

;; 'end 'call _03F4, call _044A?'
;; c_04A2()
;;  Description:
;; IN:
;;  b_9A70[4] == index of sound
;; OUT:
;;  ...
c_04A2:   ; galagao $04A2
04B1: 21 74 9A                ld   hl,$9A74         ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] d_0703[ actv_snd_idx * 3 ]
04B4: 7E                      ld   a,(hl)           
04B5: 87                      add  a,a              
04B6: 86                      add  a,(hl)           
04B7: 21 34 07                ld   hl,$0734         ; {ld hl,#d_0703_snd_parms}
04BA: D7                      rst  $10              ; HL += A
04BB: 11 75 9A                ld   de,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] memcpy( snd_parms_set, d_0703[ actv_snd_idx * 3 ], 3 )
04BE: 01 03 00                ld   bc,$0003         
04C1: ED B0                   ldir                  

;; if challenge stage default melody
04C3: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] if (actv_snd_idx == $0E) ...
04C6: FE 0E                   cp   $0E              
04C8: 20 18                   jr   nz,$04E2         ; -> l_04D3

;; if 0 == data_index
04CA: 3A 4C 9A                ld   a,($9A4C)        ; data_index, SOUND 09
04CD: A7                      and  a                
04CE: 28 0D                   jr   z,$04DD          ; -> l_04CE

;; else if 1 == data_index
04D0: 3D                      dec  a                
04D1: 28 06                   jr   z,$04D9          ; -> l_04CA

;; or if
04D3: 3A 4D 9A                ld   a,($9A4D)        ; SOUND 09
04D6: A7                      and  a                
04D7: 20 09                   jr   nz,$04E2         ; -> l_04D3
l_04CA:   ; galagao $04CA
04D9: 3E 02                   ld   a,$02            
04DB: 18 02                   jr   $04DF            ; -> l_04D0
l_04CE:   ; galagao $04CE
04DD: 3E 01                   ld   a,$01            
l_04D0:   ; galagao $04D0
04DF: 32 76 9A                ld   ($9A76),a        ; snd_parms_set.count

;; now we are checking active flags for some reason,,,,
l_04D3:   ; galagao $04D3
04E2: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] b_9AC0[ actv_snd_idx ]
04E5: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] b_9AC0[ actv_snd_idx ]
04E8: 85                      add  a,l              
04E9: 6F                      ld   l,a              
04EA: 7E                      ld   a,(hl)           
04EB: A7                      and  a                
04EC: 20 1B                   jr   nz,$0509         ; -> j_04FA
04EE: 34                      inc  (hl)             
04EF: 21 76 9A                ld   hl,$9A76         ; snd_parms_set.count
04F2: 46                      ld   b,(hl)           

;; memset( &snd_fx_dat_idx[ snd_parms_set.idx ], 0, snd_parms_set.count )
04F3: 48                      ld   c,b              
04F4: 21 30 9A                ld   hl,$9A30         ; [b_9A30] snd_fx_dat_idx[ snd_parms_set.idx ]
04F7: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
04FA: 85                      add  a,l              
04FB: 6F                      ld   l,a              
04FC: AF                      xor  a                
04FD: DF                      rst  $18              ; memset((HL), A=fill, B=ct)

;; memset( &sound_fx_status[ snd_parms_set.idx ], 0, snd_parms_set.count )
04FE: 41                      ld   b,c              
04FF: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ]
0502: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0505: 85                      add  a,l              
0506: 6F                      ld   l,a              
0507: AF                      xor  a                
0508: DF                      rst  $18              ; memset((HL), A=fill, B=ct)
j_04FA:   ; galagao $04FA
l_04FA_while:   ; galagao $04FA
0509: CD 81 05                call $0581            ; -> c_0550

;; while ( snd_parms_set.count > 0 ) ...
050C: 21 76 9A                ld   hl,$9A76         ; snd_parms_set.count--
050F: 35                      dec  (hl)             
0510: 28 0A                   jr   z,$051C          ; -> l_050D
0512: 21 75 9A                ld   hl,$9A75         ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx++
0515: 34                      inc  (hl)             
0516: 21 77 9A                ld   hl,$9A77         ; snd_parms_set.voice_select++
0519: 34                      inc  (hl)             
051A: 18 ED                   jr   $0509            ; -> j_04FA  {jr l_04FA_while}
l_050D:   ; galagao $050D
051C: 3A 78 9A                ld   a,($9A78)        ; [$9A78: 08:] ret z
051F: A7                      and  a                
0520: C8                      ret  z                
0521: AF                      xor  a                
0522: 32 78 9A                ld   ($9A78),a        ; [$9A78: 08:] 0

;; clear the sound_active flag for this one
0525: 21 C0 9A                ld   hl,$9AC0         ; [b_9AC0: Active flags of each sound effect] b_9AC0[ actv_snd_idx ] = 0
0528: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] _fx[actv_snd_idx ]
052B: 85                      add  a,l              
052C: 6F                      ld   l,a              
052D: 36 00                   ld   (hl),$00         

;; exactly the same as c_0375 until here ...  update the count/enable register for certain sound-effects
052F: 21 A0 9A                ld   hl,$9AA0         ; {ld hl,#ds_9AA0} _fx[ actv_snd_idx ] ... count/enable register
0532: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] _fx[actv_snd_idx ]
0535: 85                      add  a,l              
0536: 6F                      ld   l,a              

;; switch( actv_snd_idx )
;; case $08:
0537: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] if (actv_snd_idx == $08) ... count/enable register, coin sound
053A: FE 08                   cp   $08              
053C: 28 0F                   jr   z,$054D          ; -> l_053A_idx_8  {jr z,l_053A_idx_8}

;; case $0C:
053E: FE 0C                   cp   $0C              ; ... && if ( actv_snd_idx != $0C )
0540: 28 0D                   jr   z,$054F          ; -> l_053C_idx_C  {jr z,l_053C_idx_C}

;; case $14:
0542: FE 14                   cp   $14              ; ... && if ( actv_snd_idx != $14 )  { b_9AA0[ actv_snd_idx ] = 0 ; return }
0544: 28 15                   jr   z,$055B          ; -> l_0548_idx_14  {jr z,l_0548_idx_14}
0546: FE 07                   cp   $07              ; [rev B]
0548: 28 19                   jr   z,$0563          ; [rev B]

;; default:
054A: 36 00                   ld   (hl),$00         
054C: C9                      ret                   
l_053A_idx_8:   ; galagao $053A
054D: 35                      dec  (hl)             ; _fx[idx]--
054E: C9                      ret                   

;; _fx[$0C] used as timer ... enable snd[$16] when 0 is reached
;; caller would not have called this with _9AA0[$0C] == 0 ?
l_053C_idx_C:   ; galagao $053C
054F: 35                      dec  (hl)             
0550: 28 03                   jr   z,$0555          ; -> l_0542_enable_16  {jr z,l_0542_enable_16}
0552: CB 46                   bit  0,(hl)           ; not sure significance of checking <:0>
0554: C8                      ret  z                
l_0542_enable_16:   ; galagao $0542
0555: 3E 01                   ld   a,$01            
0557: 32 B6 9A                ld   ($9AB6),a        ; [$9AB6: 16: sound mgr, hi-score dialog] 1 ... sound-fx count/enable registers, hi-score dialog?
055A: C9                      ret                   
l_0548_idx_14:   ; galagao $0548
055B: 36 00                   ld   (hl),$00         ; _fx[ actv_snd_idx ] ... count/enable register
055D: 21 B3 9A                ld   hl,$9AB3         ; [$9AB3: 13:] 1 ... sound-fx count/enable registers, bug dive attack sound
0560: 36 01                   ld   (hl),$01         
0562: C9                      ret                   
0563: 36 00                   ld   (hl),$00         ; [rev B]
0565: 21 A0 9A                ld   hl,$9AA0         ; [ds_9AA0: label for pointer+index operations] [rev B]
0568: AF                      xor  a                ; [rev B]
0569: 06 08                   ld   b,$08            ; [rev B]
056B: DF                      rst  $18              ; [rev B]
056C: 23 77 23 23 06 0C DF 21 .db   $23,$77,$23,$23,$06,$0C,$DF,$21  ; [rev B]
0574: C0 9A 06 08 DF 23 77 23 .db   $C0,$9A,$06,$08,$DF,$23,$77,$23  ; [rev B]
057C: 23 06 0C DF C9          .db   $23,$06,$0C,$DF,$C9  ; [rev B]

;; end 'call _04A2'
;; c_0550()
;;  Description:
;; IN:
;;  ...
;; OUT:
;;  ...
c_0550:   ; galagao $0550
0581: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ]++
0584: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0587: 85                      add  a,l              
0588: 6F                      ld   l,a              
0589: 34                      inc  (hl)             

;; get a pointer to the sound effect data structure from the table
058A: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] p_snd_fx[ 2 * snd_parms_set.idx ]
058D: 21 79 07                ld   hl,$0779         ; {ld hl,#d_0748_p_snd_fx}
0590: CF                      rst  $08              ; HL += 2A
0591: 5E                      ld   e,(hl)           
0592: 23                      inc  hl               
0593: 56                      ld   d,(hl)           
0594: EB                      ex   de,hl            

;; copy first 3 bytes from the sound effect data structure (header info)
0595: 11 88 9A                ld   de,$9A88         ; [$9A88: 08: sound_effect_parms ... 3 bytes from p_snd_fx[ 2 * snd_parms_set.idx ]] memcpy( sound_effect_hdr[0], p_sndfx_data[ idx ], 3 )
0598: 01 03 00                ld   bc,$0003         
059B: ED B0                   ldir                  

;; 9A30[snd_parms_set.idx] holds the data offset i.e. snd_fx_data[ 3 + n ]
059D: EB                      ex   de,hl            ; DE = &snd_fx_data[ 3 ]
059E: 21 30 9A                ld   hl,$9A30         ; [b_9A30] snd_fx_dat_idx[ snd_parms_set.idx ]
05A1: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
05A4: 85                      add  a,l              
05A5: 6F                      ld   l,a              
05A6: 7E                      ld   a,(hl)           
05A7: EB                      ex   de,hl            ; HL = &snd_fx_data[ 3 ]
05A8: D7                      rst  $10              ; HL += A
05A9: 22 7A 9A                ld   ($9A7A),hl       ; [$9A7A: 0A: tmp pointer to sound-effect data in c_0550] save the pointer ... &snd_fx_data[ 3 + n ]

;; if ( $FF == *p_snd_fx_data )  ... close voice && exit
05AC: 7E                      ld   a,(hl)           
05AD: 3C                      inc  a                
05AE: CA BC 06                jp   z,$06BC          ; -> j_068B_close_voice_and_exit  {jp z,j_068B_close_voice_and_exit}

;; tmp_ptr = *( b_9A70[ $0A ] )
;; d_06A9_ndat[  *( tmp_ptr ) & 0x0F  * 2 ]  ... lo-nibble of sound-effect data is index into note-data
05B1: 11 DA 06                ld   de,$06DA         ; {ld de,#d_06A9_ndat}
05B4: 2A 7A 9A                ld   hl,($9A7A)       ; [$9A7A: 0A: tmp pointer to sound-effect data in c_0550] reload the current pointer to sound-effect data
05B7: 7E                      ld   a,(hl)           
05B8: E6 0F                   and  $0F              
05BA: EB                      ex   de,hl            
05BB: CF                      rst  $08              ; HL += 2A ... word pointer into note-data
05BC: 4E                      ld   c,(hl)           
05BD: 23                      inc  hl               
05BE: 46                      ld   b,(hl)           

;; use the hi-nibble of sound-effect data ....
05BF: EB                      ex   de,hl            
05C0: 7E                      ld   a,(hl)           
05C1: 0F                      rrca                  
05C2: 0F                      rrca                  
05C3: 0F                      rrca                  
05C4: 0F                      rrca                  
05C5: E6 0F                   and  $0F              

;; ... raised to power-of-two as divisor if non-zero:
;; while ( 0 != A ) ...
05C7: 28 07                   jr   z,$05D0          ; -> l_059F
l_0598:   ; galagao $0598
05C9: CB 38                   srl  b                
05CB: CB 19                   rr   c                
05CD: 3D                      dec  a                
05CE: 20 F9                   jr   nz,$05C9         ; -> l_0598

;; switch( voice_select )
l_059F:   ; galagao $059F
05D0: 3A 77 9A                ld   a,($9A77)        ; snd_parms_set.voice_select
05D3: A7                      and  a                
05D4: 28 0D                   jr   z,$05E3          ; -> l_05B2
05D6: 3D                      dec  a                
05D7: 28 05                   jr   z,$05DE          ; -> l_05AD
05D9: 21 6B 9A                ld   hl,$9A6B         ; freq 2
05DC: 18 08                   jr   $05E6            ; -> l_05B5
l_05AD:   ; galagao $05AD
05DE: 21 66 9A                ld   hl,$9A66         ; freq 1
05E1: 18 03                   jr   $05E6            ; -> l_05B5
l_05B2:   ; galagao $05B2
05E3: 21 61 9A                ld   hl,$9A61         ; freq 0

;; shift out 4 nibbles from lsn to msn (only low 4-bits of each register)
l_05B5:   ; galagao $05B5
05E6: 71                      ld   (hl),c           ; lo-byte of dw_06A9_ndat divided by hi-nibble of sound-effect ^ 2
05E7: 7E                      ld   a,(hl)           ; why not ld from C?
05E8: 0F                      rrca                  
05E9: 0F                      rrca                  
05EA: 0F                      rrca                  
05EB: 0F                      rrca                  
05EC: 23                      inc  hl               
05ED: 77                      ld   (hl),a           
05EE: 23                      inc  hl               
05EF: 70                      ld   (hl),b           ; hi-byte of dw_06A9_ndat divided by hi-nibble of sound-effect ^ 2
05F0: 7E                      ld   a,(hl)           ; why not ld from B?
05F1: 0F                      rrca                  
05F2: 0F                      rrca                  
05F3: 0F                      rrca                  
05F4: 0F                      rrca                  
05F5: 23                      inc  hl               
05F6: 77                      ld   (hl),a           

;; switch( voice_select )
05F7: 3A 77 9A                ld   a,($9A77)        ; snd_parms_set.voice_select
05FA: A7                      and  a                
05FB: 28 0D                   jr   z,$060A          ; -> l_05D9
05FD: 3D                      dec  a                
05FE: 28 05                   jr   z,$0605          ; -> l_05D4
0600: 11 6F 9A                ld   de,$9A6F         ; vol 2
0603: 18 08                   jr   $060D            ; -> l_05DC
l_05D4:   ; galagao $05D4
0605: 11 6A 9A                ld   de,$9A6A         ; vol 1
0608: 18 03                   jr   $060D            ; -> l_05DC
l_05D9:   ; galagao $05D9
060A: 11 65 9A                ld   de,$9A65         ; vol 0

;; if ( $0C != *p_snd_fx_data ) ...
l_05DC:   ; galagao $05DC
060D: 2A 7A 9A                ld   hl,($9A7A)       ; [$9A7A: 0A: tmp pointer to sound-effect data in c_0550] reload the pointer ... p_snd_fx_data = b_9A70[ $0A ]
0610: 7E                      ld   a,(hl)           
0611: D6 0C                   sub  $0C              
0613: 28 44                   jr   z,$0659          ; -> l_0628
0615: 3A 88 9A                ld   a,($9A88)        ; [$9A88: 08: sound_effect_parms ... 3 bytes from p_snd_fx[ 2 * snd_parms_set.idx ]] if ( sound_effect_hdr[0] == 0 ) .. else  if ( sound_effect_hdr[0] == 1 )
0618: A7                      and  a                
0619: 28 23                   jr   z,$063E          ; -> l_060D
061B: 3D                      dec  a                
061C: 28 10                   jr   z,$062E          ; -> l_05FD_  {jr z,l_05FD_}

;; 05ED
061E: 21 00 9A                ld   hl,$9A00         ; [b_9A00] if ( sound_fx_status[ snd_parms_set.idx ] >= 6 )
0621: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0624: 85                      add  a,l              
0625: 6F                      ld   l,a              
0626: 7E                      ld   a,(hl)           
0627: FE 06                   cp   $06              
0629: 30 13                   jr   nc,$063E         ; -> l_060D
062B: 2F                      cpl                   
062C: 18 30                   jr   $065E            ; -> l_062D
l_05FD_:   ; galagao $05FD
062E: 21 00 9A                ld   hl,$9A00         ; [b_9A00] if ( sound_fx_status[ snd_parms_set.idx ] >= 6 )
0631: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0634: 85                      add  a,l              
0635: 6F                      ld   l,a              
0636: 7E                      ld   a,(hl)           
0637: FE 06                   cp   $06              
0639: 30 03                   jr   nc,$063E         ; -> l_060D
063B: 87                      add  a,a              ; this is the only difference to the previous section!
063C: 18 20                   jr   $065E            ; -> l_062D
l_060D:   ; galagao $060D
063E: 3A 89 9A                ld   a,($9A89)        ; sound_effect_hdr[1]
0641: A7                      and  a                
0642: 28 18                   jr   z,$065C          ; -> l_062B
0644: 47                      ld   b,a              ; b_9A80_8[ 1 ]
0645: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ]
0648: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
064B: 85                      add  a,l              
064C: 6F                      ld   l,a              
064D: 7E                      ld   a,(hl)           
064E: 90                      sub  b                
064F: 38 0B                   jr   c,$065C          ; -> l_062B
0651: D6 0A                   sub  $0A              
0653: 30 04                   jr   nc,$0659         ; -> l_0628
0655: ED 44                   neg                   
0657: 18 05                   jr   $065E            ; -> l_062D
l_0628:   ; galagao $0628
0659: AF                      xor  a                
065A: 18 02                   jr   $065E            ; -> l_062D
l_062B:   ; galagao $062B
065C: 3E 0A                   ld   a,$0A            
l_062D:   ; galagao $062D
065E: 12                      ld   (de),a           ; volume ... (9A65 etc)
065F: 21 70 9A                ld   hl,$9A70         ; [b_9A70: 00: voice 0 wave select] b_9A70_wave_select[ voice_select ] = b_9A80_sound_effect_parms.wave
0662: 3A 77 9A                ld   a,($9A77)        ; snd_parms_set.voice_select
0665: 85                      add  a,l              
0666: 6F                      ld   l,a              
0667: 3A 8A 9A                ld   a,($9A8A)        ; sound_effect_hdr.wave
066A: 77                      ld   (hl),a           

;; get base multiplier
066B: 21 D7 07                ld   hl,$07D7         ; base_multipliers[ actv_snd_idx  ]
066E: 3A 74 9A                ld   a,($9A74)        ; [$9A74: 04: actv_snd_idx... index of sound currently being processed] A = d_07A6[ actv_snd_idx ]
0671: D7                      rst  $10              ; HL += A
0672: 7E                      ld   a,(hl)           

;; Multiplier = second byte of sound fx data pair
0673: 2A 7A 9A                ld   hl,($9A7A)       ; [$9A7A: 0A: tmp pointer to sound-effect data in c_0550] b_9A70[ $0A  ] + 1 ... reload pointer and increment
0676: 23                      inc  hl               
0677: 5E                      ld   e,(hl)           
0678: 16 00                   ld   d,$00            
067A: 21 00 00                ld   hl,$0000         

;; Multiply by weighting each bit of the base by the multiplier in E and adding.
067D: 06 08                   ld   b,$08            
l_064E_do_while:   ; galagao $064E
067F: CB 3F                   srl  a                
0681: 30 01                   jr   nc,$0684         ; -> l_0653
0683: 19                      add  hl,de            
l_0653:   ; galagao $0653
0684: CB 23                   sla  e                
0686: CB 12                   rl   d                
0688: 10 F5                   djnz $067F            ; -> l_064E_do_while  {djnz l_064E_do_while}
068A: 45                      ld   b,l              

;; return if count is elapsed
068B: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ]
068E: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
0691: 85                      add  a,l              
0692: 6F                      ld   l,a              
0693: 78                      ld   a,b              
0694: BE                      cp   (hl)             
0695: C0                      ret  nz               

;; update the data pointer and count registers
0696: 21 30 9A                ld   hl,$9A30         ; [b_9A30] snd_fx_dat_idx[ snd_parms_set.idx ] += 2
0699: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
069C: 85                      add  a,l              
069D: 6F                      ld   l,a              
069E: 34                      inc  (hl)             
069F: 34                      inc  (hl)             
06A0: 21 00 9A                ld   hl,$9A00         ; [b_9A00] sound_fx_status[ snd_parms_set.idx ] = 0
06A3: 3A 75 9A                ld   a,($9A75)        ; [$9A75: 05: snd_parms_set[] ... current set of sound parameters copied from snd_parms_dat] snd_parms_set.idx
06A6: 85                      add  a,l              
06A7: 6F                      ld   l,a              
06A8: 36 00                   ld   (hl),$00         
06AA: C9                      ret                   

;; This is just sort of stuck here. It is called by the handler for NMI
;; Clears the special function registers for cpu-sub2.
;; It doesn't appear that it is ever called.
l_067A_reset_sfrs:   ; galagao $067A
06AB: 21 00 9A                ld   hl,$9A00         ; [b_9A00] memset(b_9A00, 0, $0100)
06AE: 36 00                   ld   (hl),$00         
06B0: 11 01 9A                ld   de,$9A01         ; memset(b_9A00, 0, $0100)
06B3: 01 FF 00                ld   bc,$00FF         
06B6: ED B0                   ldir                  
06B8: 31 00 9B                ld   sp,$9B00         ; {ld sp,#_stack_cpu_sub2 + 0x20}
06BB: C9                      ret                   

;; set the selected voice volume to 0
;; switch( b_voice_select )
j_068B_close_voice_and_exit:   ; galagao $068B
06BC: 3A 77 9A                ld   a,($9A77)        ; snd_parms_set.voice_select
06BF: A7                      and  a                
06C0: 28 0D                   jr   z,$06CF          ; -> l_069E
06C2: 3D                      dec  a                
06C3: 28 05                   jr   z,$06CA          ; -> l_0699

;; case 2
06C5: 21 6F 9A                ld   hl,$9A6F         ; vol 2
06C8: 18 08                   jr   $06D2            ; -> l_06A1

;; case 1
l_0699:   ; galagao $0699
06CA: 21 6A 9A                ld   hl,$9A6A         ; vol 1
06CD: 18 03                   jr   $06D2            ; -> l_06A1

;; case 0
l_069E:   ; galagao $069E
06CF: 21 65 9A                ld   hl,$9A65         ; vol 0
l_06A1:   ; galagao $06A1
06D2: 36 00                   ld   (hl),$00         
06D4: 3E 01                   ld   a,$01            
06D6: 32 78 9A                ld   ($9A78),a        ; [$9A78: 08:] 1 ... sound is finished
06D9: C9                      ret                   

;; Note frequency data:
;; Base frequency values are indexed by lower-nibble of sound effect data. The
;; hi-nibble of sound effect data gives the number of octaves below the base at
;; which the final frequency occurs.
d_06A9_ndat:   ; galagao $06A9
06DA: 50 81                   .db   $50,$81  ; $00
06DC: 00 89                   .db   $00,$89  ; $01
06DE: 26 91                   .db   $26,$91  ; $02
06E0: C8 99                   .db   $C8,$99  ; $03
06E2: EC A2                   .db   $EC,$A2  ; $04
06E4: 9D AC                   .db   $9D,$AC  ; $05
06E6: E0 B6                   .db   $E0,$B6  ; $06
06E8: C0 C1                   .db   $C0,$C1  ; $07
06EA: 45 CD                   .db   $45,$CD  ; $08
06EC: 7A D9                   .db   $7A,$D9  ; $09
06EE: 69 E6                   .db   $69,$E6  ; $0A
06F0: 1C F4                   .db   $1C,$F4  ; $0B
06F2: 00 00                   .db   $00,$00  ; $0C
d_06C3:   ; galagao $06C3
06F4: 30 01 68 01 36 01 A8 01 .db   $30,$01,$68,$01,$36,$01,$A8,$01
06FC: 68 01 00 02 AC 01 08 02 .db   $68,$01,$00,$02,$AC,$01,$08,$02

;; d_06D3:
0704: 00 FE 58 FE 08 FE 98 FE .db   $00,$FE,$58,$FE,$08,$FE,$98,$FE
070C: 58 FE D0 FE 98 FE D6 FE .db   $58,$FE,$D0,$FE,$98,$FE,$D6,$FE
0714: 00 5B 00 6C 00 5B 00 7E .db   $00,$5B,$00,$6C,$00,$5B,$00,$7E
071C: 00 6C 00 97 00 81 00 99 .db   $00,$6C,$00,$97,$00,$81,$00,$99
0724: 00 D9 00 B6 00 D9 00 97 .db   $00,$D9,$00,$B6,$00,$D9,$00,$97
072C: 00 B6 00 7E 00 99 00 81 .db   $00,$B6,$00,$7E,$00,$99,$00,$81

;; snd_parms_dat[] : sound parameters
;; [0] ptr_idx ... offset in words to data ptr in p_snd_fx[], and also b_9A00[], b_9A00[$30]
;; [1] ... number of data pointers used by the sound effect data group (number of simultaneous voices) in that time slice
;; [2] voice_select
d_0703_snd_parms:   ; galagao $0703
0734: 00 01 00                .db   $00,$01,$00
0737: 01 01 01                .db   $01,$01,$01
073A: 02 01 01                .db   $02,$01,$01
073D: 03 01 01                .db   $03,$01,$01
0740: 04 01 01                .db   $04,$01,$01
0743: 05 01 00                .db   $05,$01,$00
0746: 06 01 00                .db   $06,$01,$00
0749: 20 03 00                .db   $20,$03,$00
074C: 0A 03 00                .db   $0A,$03,$00
074F: 0D 03 00                .db   $0D,$03,$00
0752: 07 03 00                .db   $07,$03,$00
0755: 13 03 00                .db   $13,$03,$00
0758: 16 03 00                .db   $16,$03,$00
075B: 19 03 00                .db   $19,$03,$00
075E: 1C 03 00                .db   $1C,$03,$00
0761: 1F 01 02                .db   $1F,$01,$02
0764: 2C 03 00                .db   $2C,$03,$00
0767: 10 03 00                .db   $10,$03,$00
076A: 23 01 00                .db   $23,$01,$00
076D: 24 01 00                .db   $24,$01,$00  ; $13
0770: 25 03 00                .db   $25,$03,$00
0773: 28 01 00                .db   $28,$01,$00
0776: 29 03 00                .db   $29,$03,$00

;; Pointers into sound effect data tables (d_07BD and beyond) loaded by c_0550
;; Pointer selection by b_9A70[5] ... snd_parms_set.idx
;; Ordering of these elements is used also to index byte tables at 9A00 and 9A30.
d_0748_p_snd_fx:   ; galagao $0748
0779: EE 07                   .db   $EE,$07  ; 0
077B: 45 08                   .db   $45,$08  ; 1
077D: 23 08                   .db   $23,$08  ; 2
077F: EF 07                   .db   $EF,$07  ; 3
0781: 8F 08                   .db   $8F,$08  ; 4
0783: A9 08                   .db   $A9,$08  ; 5
0785: BD 08                   .db   $BD,$08  ; 6
0787: 03 0A                   .db   $03,$0A  ; 7
0789: 13 0A                   .db   $13,$0A  ; 8
078B: 23 0A                   .db   $23,$0A  ; 9
078D: CD 09                   .db   $CD,$09  ; 10
078F: DF 09                   .db   $DF,$09  ; 11
0791: F1 09                   .db   $F1,$09  ; 12
0793: 33 0A                   .db   $33,$0A  ; 13
0795: 77 0A                   .db   $77,$0A  ; 14
0797: BB 0A                   .db   $BB,$0A  ; 15
0799: E7 0A                   .db   $E7,$0A  ; 16
079B: 2B 0B                   .db   $2B,$0B  ; 17
079D: 6F 0B                   .db   $6F,$0B  ; 18
079F: D1 08                   .db   $D1,$08  ; 19
07A1: 1D 09                   .db   $1D,$09  ; 20
07A3: 67 09                   .db   $67,$09  ; 21
07A5: 8D 0C                   .db   $8D,$0C  ; 22
07A7: 1B 0D                   .db   $1B,$0D  ; 23
07A9: 69 0D                   .db   $69,$0D  ; 24
07AB: 97 09                   .db   $97,$09  ; 25
07AD: A9 09                   .db   $A9,$09  ; 26
07AF: BB 09                   .db   $BB,$09  ; 27
07B1: D1 08                   .db   $D1,$08  ; 28
07B3: D1 08                   .db   $D1,$08  ; 29
07B5: D1 08                   .db   $D1,$08  ; 30
07B7: 39 0C                   .db   $39,$0C  ; 31
07B9: 9B 0B                   .db   $9B,$0B  ; 32
07BB: D1 0B                   .db   $D1,$0B  ; 33
07BD: 07 0C                   .db   $07,$0C  ; 34
07BF: 25 0C                   .db   $25,$0C  ; 35
07C1: 39 0C                   .db   $39,$0C  ; 36
07C3: 9D 0D                   .db   $9D,$0D  ; 37
07C5: 11 0E                   .db   $11,$0E  ; 38
07C7: 8D 0E                   .db   $8D,$0E  ; 39
07C9: 8F 0D                   .db   $8F,$0D  ; 40
07CB: 11 0D                   .db   $11,$0D  ; 41
07CD: 5F 0D                   .db   $5F,$0D  ; 42
07CF: 85 0D                   .db   $85,$0D  ; 43
07D1: CF 0E                   .db   $CF,$0E  ; 44
07D3: 0B 0F                   .db   $0B,$0F  ; 45
07D5: 47 0F                   .db   $47,$0F  ; 46

;; indexed by active sound index, multiply by second byte of sound data pair
d_07A6:   ; galagao $07A6
07D7: 04 02 02 02 02 04 04 0A .db   $04,$02,$02,$02,$02,$04,$04,$0A
07DF: 07 0C 0B 04 0A 0D 04 01 .db   $07,$0C,$0B,$04,$0A,$0D,$04,$01
07E7: 04 0C 02 06 05 02 0A    .db   $04,$0C,$02,$06,$05,$02,$0A

;; sound effect data:
;; header-info, stored at 9A80_8[]
;; [0]
;; [1]
;; [2]: wave table index
;; byte_pairs * n
;; [0]: lo-nibble is index into frequency tbl
;; hi-nibble^2 = divisor to note frequency
;; [1]
;; [n] 0xFF
d_07BD:   ; galagao $07BD
07EE: FF                      .db   $FF
d_07BE:   ; galagao $07BE
07EF: 00 00 06                .db   $00,$00,$06
07F2: 71 01 72 01 73 01 75 01 .db   $71,$01,$72,$01,$73,$01,$75,$01
07FA: 74 01 73 01 72 01 71 01 .db   $74,$01,$73,$01,$72,$01,$71,$01
0802: 70 01 8B 01 8A 01 0C 04 .db   $70,$01,$8B,$01,$8A,$01,$0C,$04
080A: 86 01 87 01 88 01 89 01 .db   $86,$01,$87,$01,$88,$01,$89,$01
0812: 8A 01 89 01 88 01 87 01 .db   $8A,$01,$89,$01,$88,$01,$87,$01
081A: 86 01 85 01 84 01 83 01 .db   $86,$01,$85,$01,$84,$01,$83,$01
0822: FF                      .db   $FF
d_07F2:   ; galagao $07F2
0823: 00 00 04 88 01 8A 01 70 .db   $00,$00,$04,$88,$01,$8A,$01,$70
082B: 01 71 01 73 01 75 01 77 .db   $01,$71,$01,$73,$01,$75,$01,$77
0833: 01 78 01 0C 06 74 01 73 .db   $01,$78,$01,$0C,$06,$74,$01,$73
083B: 01 72 01 71 01 70 01 8B .db   $01,$72,$01,$71,$01,$70,$01,$8B
0843: 01 FF                   .db   $01,$FF
d_0814:   ; galagao $0814
0845: 00 00 07 89 01 8A 01 8B .db   $00,$00,$07,$89,$01,$8A,$01,$8B
084D: 01 0C 01 70 01 71 01 72 .db   $01,$0C,$01,$70,$01,$71,$01,$72
0855: 01 0C 01 73 01          .db   $01,$0C,$01,$73,$01
085A: 74 01 75 01 0C 03 8B 01 .db   $74,$01,$75,$01,$0C,$03,$8B,$01
0862: 70 01 71 01 0C 01 72 01 .db   $70,$01,$71,$01,$0C,$01,$72,$01
086A: 73 01 74 01 0C 01 75 01 .db   $73,$01,$74,$01,$0C,$01,$75,$01
0872: 76 01 77 01 0C 03 71 01 .db   $76,$01,$77,$01,$0C,$03,$71,$01
087A: 72 01 73 01 0C 01 74 01 .db   $72,$01,$73,$01,$0C,$01,$74,$01
0882: 75 01 76 01 0C 01 77 01 .db   $75,$01,$76,$01,$0C,$01,$77,$01
088A: 78 01 79 01 FF          .db   $78,$01,$79,$01,$FF
d_085E:   ; galagao $085E
088F: 00 00 05 71 01 72 01 73 .db   $00,$00,$05,$71,$01,$72,$01,$73
0897: 01 0C 01                .db   $01,$0C,$01
089A: 74 01 75 01 76 01 0C 01 .db   $74,$01,$75,$01,$76,$01,$0C,$01
08A2: 77 01 78 01 79 01 FF    .db   $77,$01,$78,$01,$79,$01,$FF
d_0878:   ; galagao $0878
08A9: 00 00 04 61 01 7A 01 60 .db   $00,$00,$04,$61,$01,$7A,$01,$60
08B1: 01 78 01 7A 01 76 01 78 .db   $01,$78,$01,$7A,$01,$76,$01,$78
08B9: 01 75 01 FF             .db   $01,$75,$01,$FF
d_088C:   ; galagao $088C
08BD: 00 00 00 76 01 79 01 60 .db   $00,$00,$00,$76,$01,$79,$01,$60
08C5: 01 63 01 66 01          .db   $01,$63,$01,$66,$01
08CA: 63 01 60 01 79 01 FF    .db   $63,$01,$60,$01,$79,$01,$FF
d_08A0:   ; galagao $08A0
08D1: 00 00 07 81 08 81 01 86 .db   $00,$00,$07,$81,$08,$81,$01,$86
08D9: 03                      .db   $03
08DA: 88 09 8B 03 8A 09 86 03 .db   $88,$09,$8B,$03,$8A,$09,$86,$03
08E2: 88 09 73 03 71 09 86 03 .db   $88,$09,$73,$03,$71,$09,$86,$03
08EA: 88 09 8B 03 8A 09 86 03 .db   $88,$09,$8B,$03,$8A,$09,$86,$03
08F2: 71 09 75 03 76 09 74 03 .db   $71,$09,$75,$03,$76,$09,$74,$03
08FA: 72 09 71 03 8B 09 89 03 .db   $72,$09,$71,$03,$8B,$09,$89,$03
0902: 88 09 84 03 74 09 76 03 .db   $88,$09,$84,$03,$74,$09,$76,$03
090A: 74 09 71 03 73 04 8B 04 .db   $74,$09,$71,$03,$73,$04,$8B,$04
0912: 88 04 71 04 8A 04 88 04 .db   $88,$04,$71,$04,$8A,$04,$88,$04
091A: 0C 10 FF                .db   $0C,$10,$FF
d_08EC:   ; galagao $08EC
091D: 00 00 06 8A 09 81 03 88 .db   $00,$00,$06,$8A,$09,$81,$03,$88
0925: 09 83 03 86 09          .db   $09,$83,$03,$86,$09
092A: 81 03 83 09 85 03 8A 09 .db   $81,$03,$83,$09,$85,$03,$8A,$09
0932: 81 03 88 09 83 03 86 09 .db   $81,$03,$88,$09,$83,$03,$86,$09
093A: 81 03 88 09 71 03 72 09 .db   $81,$03,$88,$09,$71,$03,$72,$09
0942: 71 03 8B 09 89 03 88 09 .db   $71,$03,$8B,$09,$89,$03,$88,$09
094A: 86 03 84 09 88 03 89 09 .db   $86,$03,$84,$09,$88,$03,$89,$09
0952: 8B 03 89 09 86 03 8B 04 .db   $8B,$03,$89,$09,$86,$03,$8B,$04
095A: 88 04 83 04 88 04 85 04 .db   $88,$04,$83,$04,$88,$04,$85,$04
0962: 83 04 0C 10 FF          .db   $83,$04,$0C,$10,$FF
d_0936:   ; galagao $0936
0967: 00 00 07 81 0C 83 09 86 .db   $00,$00,$07,$81,$0C,$83,$09,$86
096F: 03 85 0C 81 0C 86 0C 88 .db   $03,$85,$0C,$81,$0C,$86,$0C,$88
0977: 09 8B 03                .db   $09,$8B,$03
097A: 8A 0C 88 0C 89 0C 88 09 .db   $8A,$0C,$88,$0C,$89,$0C,$88,$09
0982: 86 03 84 0C 89 0C 74 0C .db   $86,$03,$84,$0C,$89,$0C,$74,$0C
098A: 71 09 89 03 88 0C 71 09 .db   $71,$09,$89,$03,$88,$0C,$71,$09
0992: 8A 03 0C 10 FF          .db   $8A,$03,$0C,$10,$FF
d_0966:   ; galagao $0966
0997: 02 00 03                .db   $02,$00,$03
099A: 78 02 0C 01 78 01 79 01 .db   $78,$02,$0C,$01,$78,$01,$79,$01
09A2: 7B 01 61 03 0C 03 FF    .db   $7B,$01,$61,$03,$0C,$03,$FF
d_0978:   ; galagao $0978
09A9: 02 00 03 73 02 0C 01 73 .db   $02,$00,$03,$73,$02,$0C,$01,$73
09B1: 01 74 01 76 01 78 03 0C .db   $01,$74,$01,$76,$01,$78,$03,$0C
09B9: 02                      .db   $02
09BA: FF                      .db   $FF
d_098A:   ; galagao $098A
09BB: 02 00 03 70 02 0C 01 70 .db   $02,$00,$03,$70,$02,$0C,$01,$70
09C3: 01 71 01 73 01 75 03 0C .db   $01,$71,$01,$73,$01,$75,$03,$0C
09CB: 02 FF                   .db   $02,$FF
d_099C:   ; galagao $099C
09CD: 01 00 04 78 01 7A 01 63 .db   $01,$00,$04,$78,$01,$7A,$01,$63
09D5: 01 78 01 7A 01 63 01 65 .db   $01,$78,$01,$7A,$01,$63,$01,$65
09DD: 03 FF                   .db   $03,$FF
d_09AE:   ; galagao $09AE
09DF: 01 00 05 73 01 78 01 7A .db   $01,$00,$05,$73,$01,$78,$01,$7A
09E7: 01 73 01 78 01 7A 01 60 .db   $01,$73,$01,$78,$01,$7A,$01,$60
09EF: 03 FF                   .db   $03,$FF
d_09C0:   ; galagao $09C0
09F1: 01 00 07 8A 01 73 01 78 .db   $01,$00,$07,$8A,$01,$73,$01,$78
09F9: 01 8A 01 73 01 78 01 7A .db   $01,$8A,$01,$73,$01,$78,$01,$7A
0A01: 03 FF                   .db   $03,$FF
d_09D2:   ; galagao $09D2
0A03: 01 06 04 7A 01 78 01 7A .db   $01,$06,$04,$7A,$01,$78,$01,$7A
0A0B: 01 61 01 65 01 68 03 FF .db   $01,$61,$01,$65,$01,$68,$03,$FF
d_09E2:   ; galagao $09E2
0A13: 01 06 04 78 01 75 01 78 .db   $01,$06,$04,$78,$01,$75,$01,$78
0A1B: 01 7A 01 61 01 65 03 FF .db   $01,$7A,$01,$61,$01,$65,$03,$FF
d_09F2:   ; galagao $09F2
0A23: 01 06 04 75 01 71 01 75 .db   $01,$06,$04,$75,$01,$71,$01,$75
0A2B: 01 78 01 7A 01 60 03 FF .db   $01,$78,$01,$7A,$01,$60,$03,$FF
d_0A02:   ; galagao $0A02
0A33: 02 04 03 7A 01 76 01 78 .db   $02,$04,$03,$7A,$01,$76,$01,$78
0A3B: 01 75 01 76 01 73 01 75 .db   $01,$75,$01,$76,$01,$73,$01,$75
0A43: 01 72 01 73 01 8A 01    .db   $01,$72,$01,$73,$01,$8A,$01
0A4A: 8B 01 88 01 86 01 85 01 .db   $8B,$01,$88,$01,$86,$01,$85,$01
0A52: 83 01 82 01 83 01 86 01 .db   $83,$01,$82,$01,$83,$01,$86,$01
0A5A: 85 01 88 01 86 01 8A 01 .db   $85,$01,$88,$01,$86,$01,$8A,$01
0A62: 88 01 8B 01 8A 01 73 01 .db   $88,$01,$8B,$01,$8A,$01,$73,$01
0A6A: 72 01 73 01 75 01 8A 01 .db   $72,$01,$73,$01,$75,$01,$8A,$01
0A72: 70 01 72 01 FF          .db   $70,$01,$72,$01,$FF
d_0A46:   ; galagao $0A46
0A77: 02 04 03 76 01 73 01 75 .db   $02,$04,$03,$76,$01,$73,$01,$75
0A7F: 01 72 01 73 01 70 01 72 .db   $01,$72,$01,$73,$01,$70,$01,$72
0A87: 01 8A 01                .db   $01,$8A,$01
0A8A: 8B 01 86 01 88 01 85 01 .db   $8B,$01,$86,$01,$88,$01,$85,$01
0A92: 83 01 82 01 80 01 9A 01 .db   $83,$01,$82,$01,$80,$01,$9A,$01
0A9A: 9A 01 83 01 82 01 85 01 .db   $9A,$01,$83,$01,$82,$01,$85,$01
0AA2: 83 01 86 01 85 01 88 01 .db   $83,$01,$86,$01,$85,$01,$88,$01
0AAA: 86 01 8A 01 88 01 8B 01 .db   $86,$01,$8A,$01,$88,$01,$8B,$01
0AB2: 8A 01 88 01 86 01 85 01 .db   $8A,$01,$88,$01,$86,$01,$85,$01
0ABA: FF                      .db   $FF
d_0A8A:   ; galagao $0A8A
0ABB: 02 10 03 93 02 9A 02 83 .db   $02,$10,$03,$93,$02,$9A,$02,$83
0AC3: 03 9A 01 98 01 96 01    .db   $03,$9A,$01,$98,$01,$96,$01
0ACA: 95 01 93 02 95 03 96 02 .db   $95,$01,$93,$02,$95,$03,$96,$02
0AD2: 98 02 9A 02 9B 02 9A 02 .db   $98,$02,$9A,$02,$9B,$02,$9A,$02
0ADA: 98 01 96 01 95 01 92 01 .db   $98,$01,$96,$01,$95,$01,$92,$01
0AE2: 93 01 95 01 FF          .db   $93,$01,$95,$01,$FF
d_0AB6:   ; galagao $0AB6
0AE7: 02 04 03 7A 01 77 01 78 .db   $02,$04,$03,$7A,$01,$77,$01,$78
0AEF: 01 75 01 77 01 73 01 75 .db   $01,$75,$01,$77,$01,$73,$01,$75
0AF7: 01 72 01                .db   $01,$72,$01
0AFA: 73 01 8A 01 80 01 88 01 .db   $73,$01,$8A,$01,$80,$01,$88,$01
0B02: 87 01 85 01 83 01 82 01 .db   $87,$01,$85,$01,$83,$01,$82,$01
0B0A: 83 01 87 01 85 01 88 01 .db   $83,$01,$87,$01,$85,$01,$88,$01
0B12: 87 01 8A 01 88 01 80 01 .db   $87,$01,$8A,$01,$88,$01,$80,$01
0B1A: 8A 01 73 01 72 01 73 01 .db   $8A,$01,$73,$01,$72,$01,$73,$01
0B22: 75 01 8A 01 70 01 72 01 .db   $75,$01,$8A,$01,$70,$01,$72,$01
0B2A: FF                      .db   $FF
d_0AFA:   ; galagao $0AFA
0B2B: 02 04 03 77 01 73 01 75 .db   $02,$04,$03,$77,$01,$73,$01,$75
0B33: 01 72 01 73 01 70 01    .db   $01,$72,$01,$73,$01,$70,$01
0B3A: 72 01 8A 01 80 01 87 01 .db   $72,$01,$8A,$01,$80,$01,$87,$01
0B42: 88 01 85 01 83 01 82 01 .db   $88,$01,$85,$01,$83,$01,$82,$01
0B4A: 80 01 9A 01 9A 01 83 01 .db   $80,$01,$9A,$01,$9A,$01,$83,$01
0B52: 82 01 85 01 83 01 87 01 .db   $82,$01,$85,$01,$83,$01,$87,$01
0B5A: 85 01 88 01 87 01 8A 01 .db   $85,$01,$88,$01,$87,$01,$8A,$01
0B62: 88 01 80 01 8A 01 88 01 .db   $88,$01,$80,$01,$8A,$01,$88,$01
0B6A: 87 01 85 01 FF          .db   $87,$01,$85,$01,$FF
d_0B3E:   ; galagao $0B3E
0B6F: 02 10 03 93 02 9A 02 83 .db   $02,$10,$03,$93,$02,$9A,$02,$83
0B77: 03 9A 01                .db   $03,$9A,$01
0B7A: 98 01 97 01 95 01 93 02 .db   $98,$01,$97,$01,$95,$01,$93,$02
0B82: 95 03 97 02 98 02 9A 02 .db   $95,$03,$97,$02,$98,$02,$9A,$02
0B8A: 90 02 9A 02 98 01 97 01 .db   $90,$02,$9A,$02,$98,$01,$97,$01
0B92: 95 01 92 01 93 01 95 01 .db   $95,$01,$92,$01,$93,$01,$95,$01
0B9A: FF                      .db   $FF
d_0B6A:   ; galagao $0B6A
0B9B: 02 04 03 7A 01 76 01 78 .db   $02,$04,$03,$7A,$01,$76,$01,$78
0BA3: 01 75 01 76 01 73 01    .db   $01,$75,$01,$76,$01,$73,$01
0BAA: 75 01 72 01 73 01 8A 01 .db   $75,$01,$72,$01,$73,$01,$8A,$01
0BB2: 8A 01 88 01 86 01 85 01 .db   $8A,$01,$88,$01,$86,$01,$85,$01
0BBA: 83 01 82 01 83 01 85 01 .db   $83,$01,$82,$01,$83,$01,$85,$01
0BC2: 86 01 88 01 86 01 8A 01 .db   $86,$01,$88,$01,$86,$01,$8A,$01
0BCA: 70 01 72 01 73 04 FF    .db   $70,$01,$72,$01,$73,$04,$FF
d_0BA0:   ; galagao $0BA0
0BD1: 02 04 03 76 01 73 01 75 .db   $02,$04,$03,$76,$01,$73,$01,$75
0BD9: 01                      .db   $01
0BDA: 72 01 73 01 70 01 72 01 .db   $72,$01,$73,$01,$70,$01,$72,$01
0BE2: 8A 01 8A 01 86 01 86 01 .db   $8A,$01,$8A,$01,$86,$01,$86,$01
0BEA: 85 01 83 01 82 01 80 01 .db   $85,$01,$83,$01,$82,$01,$80,$01
0BF2: 9A 01 9A 01 8B 01 80 01 .db   $9A,$01,$9A,$01,$8B,$01,$80,$01
0BFA: 82 01 83 01 85 01 86 01 .db   $82,$01,$83,$01,$85,$01,$86,$01
0C02: 88 01 8A 04 FF          .db   $88,$01,$8A,$04,$FF
d_0BD6:   ; galagao $0BD6
0C07: 02 10 03 73 02 75 02 76 .db   $02,$10,$03,$73,$02,$75,$02,$76
0C0F: 02 75 02 73 02 72 02 70 .db   $02,$75,$02,$73,$02,$72,$02,$70
0C17: 02 72 02                .db   $02,$72,$02
0C1A: 73 02 8B 02 8A 02 86 02 .db   $73,$02,$8B,$02,$8A,$02,$86,$02
0C22: 83 04 FF                .db   $83,$04,$FF
d_0BF4:   ; galagao $0BF4
0C25: 00 00 04 71 04 73 04 71 .db   $00,$00,$04,$71,$04,$73,$04,$71
0C2D: 04 73 04 76 04 78 04 76 .db   $04,$73,$04,$76,$04,$78,$04,$76
0C35: 04 78 04 FF             .db   $04,$78,$04,$FF
d_0C08:   ; galagao $0C08
0C39: 00 00 06 56 01 55 01 54 .db   $00,$00,$06,$56,$01,$55,$01,$54
0C41: 01 53 01 52 01 51 01 50 .db   $01,$53,$01,$52,$01,$51,$01,$50
0C49: 01                      .db   $01
0C4A: 6B 01 6A 01 69 01 68 01 .db   $6B,$01,$6A,$01,$69,$01,$68,$01
0C52: 67 01 66 01 65 01 64 01 .db   $67,$01,$66,$01,$65,$01,$64,$01
0C5A: 63 01 62 01 61 01 60 01 .db   $63,$01,$62,$01,$61,$01,$60,$01
0C62: 7B 01 7A 01 79 01 78 01 .db   $7B,$01,$7A,$01,$79,$01,$78,$01
0C6A: 77 01 76 01 75 01 74 01 .db   $77,$01,$76,$01,$75,$01,$74,$01
0C72: 73 01 72 01 71 01 70 01 .db   $73,$01,$72,$01,$71,$01,$70,$01
0C7A: 8B 01 8A 01 89 01 88 01 .db   $8B,$01,$8A,$01,$89,$01,$88,$01
0C82: 87 01 86 01 85 01 84 01 .db   $87,$01,$86,$01,$85,$01,$84,$01
0C8A: 83 01 FF                .db   $83,$01,$FF
d_0C5C:   ; galagao $0C5C
0C8D: 02 04 05 60 01 78 01 75 .db   $02,$04,$05,$60,$01,$78,$01,$75
0C95: 01 71 01 60 01          .db   $01,$71,$01,$60,$01
0C9A: 78 01 75 01 71 01 60 01 .db   $78,$01,$75,$01,$71,$01,$60,$01
0CA2: 78 01 75 01 71 01 60 01 .db   $78,$01,$75,$01,$71,$01,$60,$01
0CAA: 78 01 75 01 71 01 60 01 .db   $78,$01,$75,$01,$71,$01,$60,$01
0CB2: 78 01 75 01 71 01 60 01 .db   $78,$01,$75,$01,$71,$01,$60,$01
0CBA: 78 01 75 01 71 01 60 01 .db   $78,$01,$75,$01,$71,$01,$60,$01
0CC2: 0C 01 78 01 7A 01 75 01 .db   $0C,$01,$78,$01,$7A,$01,$75,$01
0CCA: 78 01 73 01 75 01 61 01 .db   $78,$01,$73,$01,$75,$01,$61,$01
0CD2: 7A 01 76 01 73 01 61 01 .db   $7A,$01,$76,$01,$73,$01,$61,$01
0CDA: 7A 01 76 01 73 01 61 01 .db   $7A,$01,$76,$01,$73,$01,$61,$01
0CE2: 7A 01 76 01 73 01 61 01 .db   $7A,$01,$76,$01,$73,$01,$61,$01
0CEA: 7A 01 76 01 73 01 61 01 .db   $7A,$01,$76,$01,$73,$01,$61,$01
0CF2: 79 01 76 01 73 01 61 01 .db   $79,$01,$76,$01,$73,$01,$61,$01
0CFA: 79 01 76 01 73 01 61 01 .db   $79,$01,$76,$01,$73,$01,$61,$01
0D02: 0C 01 79 01 61 01 78 01 .db   $0C,$01,$79,$01,$61,$01,$78,$01
0D0A: 79 01 75 01 78 01 FF    .db   $79,$01,$75,$01,$78,$01,$FF
d_0CE0:   ; galagao $0CE0
0D11: 02 02 05 60 01 60 01 60 .db   $02,$02,$05,$60,$01,$60,$01,$60
0D19: 01 FF                   .db   $01,$FF
d_0CEA:   ; galagao $0CEA
0D1B: 02 04 05 61 02 78 02 78 .db   $02,$04,$05,$61,$02,$78,$02,$78
0D23: 02 61 02 78 02 78 02    .db   $02,$61,$02,$78,$02,$78,$02
0D2A: 61 02 78 02 78 02 61 02 .db   $61,$02,$78,$02,$78,$02,$61,$02
0D32: 78 02 78 02 61 02 78 02 .db   $78,$02,$78,$02,$61,$02,$78,$02
0D3A: 7A 02 75 02 63 02 7A 02 .db   $7A,$02,$75,$02,$63,$02,$7A,$02
0D42: 7A 02 63 02 7A 02 7A 02 .db   $7A,$02,$63,$02,$7A,$02,$7A,$02
0D4A: 63 02 7A 02 79 02 63 02 .db   $63,$02,$7A,$02,$79,$02,$63,$02
0D52: 79 02 79 02 63 02 79 02 .db   $79,$02,$79,$02,$63,$02,$79,$02
0D5A: 76 02 73 02 FF          .db   $76,$02,$73,$02,$FF
d_0D2E:   ; galagao $0D2E
0D5F: 02 02 05 78 01 78 01 78 .db   $02,$02,$05,$78,$01,$78,$01,$78
0D67: 01 FF                   .db   $01,$FF
d_0D38:   ; galagao $0D38
0D69: 02 10 05 85 06 85 06 85 .db   $02,$10,$05,$85,$06,$85,$06,$85
0D71: 06 85 06 85 04 85 04 86 .db   $06,$85,$06,$85,$04,$85,$04,$86
0D79: 06                      .db   $06
0D7A: 86 06 86 06 86 06 86 04 .db   $86,$06,$86,$06,$86,$06,$86,$04
0D82: 86 04 FF                .db   $86,$04,$FF
d_0D54:   ; galagao $0D54
0D85: 02 04 05 81 01 81 01 81 .db   $02,$04,$05,$81,$01,$81,$01,$81
0D8D: 01 FF                   .db   $01,$FF
d_0D5E:   ; galagao $0D5E
0D8F: 02 00 07 65 01 0C 01 61 .db   $02,$00,$07,$65,$01,$0C,$01,$61
0D97: 01 0C 01 63 01 FF       .db   $01,$0C,$01,$63,$01,$FF
d_0D6C:   ; galagao $0D6C
0D9D: 02 00 05 7A 05 0C 01 7A .db   $02,$00,$05,$7A,$05,$0C,$01,$7A
0DA5: 01 0C 01 7A 03          .db   $01,$0C,$01,$7A,$03
0DAA: 0C 01 78 07 0C 01 78 07 .db   $0C,$01,$78,$07,$0C,$01,$78,$07
0DB2: 0C 01 78 03 0C 01 7B 05 .db   $0C,$01,$78,$03,$0C,$01,$7B,$05
0DBA: 0C 01 7B 01 0C 01 7B 03 .db   $0C,$01,$7B,$01,$0C,$01,$7B,$03
0DC2: 0C 01 7A 07 0C 01 7A 07 .db   $0C,$01,$7A,$07,$0C,$01,$7A,$07
0DCA: 0C 01 7A 03 0C 01 7B 01 .db   $0C,$01,$7A,$03,$0C,$01,$7B,$01
0DD2: 0C 01 7B 01 0C 03 7B 01 .db   $0C,$01,$7B,$01,$0C,$03,$7B,$01
0DDA: 0C 01 7B 03 0C 01 61 01 .db   $0C,$01,$7B,$03,$0C,$01,$61,$01
0DE2: 0C 01 61 01 0C 03 61 01 .db   $0C,$01,$61,$01,$0C,$03,$61,$01
0DEA: 0C 01 61 03 0C 01 61 03 .db   $0C,$01,$61,$03,$0C,$01,$61,$03
0DF2: 0C 01 61 03 0C 01 63 01 .db   $0C,$01,$61,$03,$0C,$01,$63,$01
0DFA: 0C 01 63 01 0C 03 63 01 .db   $0C,$01,$63,$01,$0C,$03,$63,$01
0E02: 0C 01 63 03 0C 01 63 03 .db   $0C,$01,$63,$03,$0C,$01,$63,$03
0E0A: 0C 01 63 03 0C 01 FF    .db   $0C,$01,$63,$03,$0C,$01,$FF
d_0DE0:   ; galagao $0DE0
0E11: 02 00 03 86 02 8A 02 71 .db   $02,$00,$03,$86,$02,$8A,$02,$71
0E19: 02                      .db   $02
0E1A: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E22: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E2A: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E32: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E3A: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E42: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E4A: 76 02 86 02 8A 02 71 02 .db   $76,$02,$86,$02,$8A,$02,$71,$02
0E52: 76 02 77 01 0C 01 77 01 .db   $76,$02,$77,$01,$0C,$01,$77,$01
0E5A: 0C 03 77 01 0C 01 77 03 .db   $0C,$03,$77,$01,$0C,$01,$77,$03
0E62: 0C 01 69 01 0C 01 69 01 .db   $0C,$01,$69,$01,$0C,$01,$69,$01
0E6A: 0C 03 69 01 0C 01 69 03 .db   $0C,$03,$69,$01,$0C,$01,$69,$03
0E72: 0C 01 69 03 0C 01 69 03 .db   $0C,$01,$69,$03,$0C,$01,$69,$03
0E7A: 0C 01 8B 02 73 02 76 02 .db   $0C,$01,$8B,$02,$73,$02,$76,$02
0E82: 7B 02 7B 02 76 02 73 02 .db   $7B,$02,$7B,$02,$76,$02,$73,$02
0E8A: 8B 02 FF                .db   $8B,$02,$FF
d_0E5C:   ; galagao $0E5C
0E8D: 00 00 02 86 08 81 08 86 .db   $00,$00,$02,$86,$08,$81,$08,$86
0E95: 08 81 08 86 08          .db   $08,$81,$08,$86,$08
0E9A: 81 08 86 08 81 08 82 01 .db   $81,$08,$86,$08,$81,$08,$82,$01
0EA2: 0C 01 82 01 0C 03 82 01 .db   $0C,$01,$82,$01,$0C,$03,$82,$01
0EAA: 0C 01 82 03 0C 01 84 01 .db   $0C,$01,$82,$03,$0C,$01,$84,$01
0EB2: 0C 01 84 01 0C 03 84 01 .db   $0C,$01,$84,$01,$0C,$03,$84,$01
0EBA: 0C 01 84 03 0C 01 84 03 .db   $0C,$01,$84,$03,$0C,$01,$84,$03
0EC2: 0C 01 84 03 0C 01 7B 08 .db   $0C,$01,$84,$03,$0C,$01,$7B,$08
0ECA: 76 04 8B 04 FF          .db   $76,$04,$8B,$04,$FF
d_0E9E:   ; galagao $0E9E
0ECF: 00 0C 05 75 0C 71 0C 8A .db   $00,$0C,$05,$75,$0C,$71,$0C,$8A
0ED7: 0C 86 0C                .db   $0C,$86,$0C
0EDA: 0C 09 75 03 71 09 8A 03 .db   $0C,$09,$75,$03,$71,$09,$8A,$03
0EE2: 86 04 8A 04 71 04 89 04 .db   $86,$04,$8A,$04,$71,$04,$89,$04
0EEA: 70 04 73 04 8B 0C 73 0C .db   $70,$04,$73,$04,$8B,$0C,$73,$0C
0EF2: 76 0C 78 0C 0C 09 79 03 .db   $76,$0C,$78,$0C,$0C,$09,$79,$03
0EFA: 76 09 72 03 8B 04 89 04 .db   $76,$09,$72,$03,$8B,$04,$89,$04
0F02: 86 04 72 04 89 04 76 04 .db   $86,$04,$72,$04,$89,$04,$76,$04
0F0A: FF                      .db   $FF
d_0EDA:   ; galagao $0EDA
0F0B: 00 0C 05 71 0C 8A 0C 86 .db   $00,$0C,$05,$71,$0C,$8A,$0C,$86
0F13: 0C 85 0C 0C 09 81 03    .db   $0C,$85,$0C,$0C,$09,$81,$03
0F1A: 8A 09 86 03 85 04 86 04 .db   $8A,$09,$86,$03,$85,$04,$86,$04
0F22: 8A 04 86 04 89 04 8B 04 .db   $8A,$04,$86,$04,$89,$04,$8B,$04
0F2A: 88 0C 8B 0C 73 0C 76 0C .db   $88,$0C,$8B,$0C,$73,$0C,$76,$0C
0F32: 0C 09 76 03 72 09 8B 03 .db   $0C,$09,$76,$03,$72,$09,$8B,$03
0F3A: 8A 04 86 04 82 04 8B 04 .db   $8A,$04,$86,$04,$82,$04,$8B,$04
0F42: 89 04 82 04 FF          .db   $89,$04,$82,$04,$FF
d_0F16:   ; galagao $0F16
0F47: 00 00 03 75 18 75 18 75 .db   $00,$00,$03,$75,$18,$75,$18,$75
0F4F: 18 71 0C 75 0C 73 18 73 .db   $18,$71,$0C,$75,$0C,$73,$18,$73
0F57: 18 72 18                .db   $18,$72,$18
0F5A: 76 0C 78 0C FF          .db   $76,$0C,$78,$0C,$FF
0F5F: 84 FF FF FF FF FF FF FF .db   $84,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F67: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F6F: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F77: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F7F: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F87: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F8F: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F97: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0F9F: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FA7: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FAF: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FB7: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FBF: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FC7: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FCF: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FD7: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FDF: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FE7: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FEF: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FF7: FF FF FF FF FF FF FF FF .db   $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF  ; [rev B]
0FFF: FF                      .db   $FF  ; [rev B]

;; ===========================================================================
;; 10 galagao source items with no place in rev. B:
;;   $0066 gg1-7.s:90  ld   a,#1
;;   $0068 gg1-7.s:91  ld   (_sfr_6822),a
;;   $006B gg1-7.s:92  xor  a
;;   $006C gg1-7.s:93  ld   (_sfr_6822),a
;;   $006F gg1-7.s:94  call c_nmi_proc
;;   $008F gg1-7.s:133  ld   a,#0x11
;;   $02B6 gg1-7.s:513  ld   a,(b_9AA0 + 0x0E)   <l_02B6>
;;   $02B9 gg1-7.s:514  and  a
;;   $02BA gg1-7.s:515  jr   z,l_02C6
;;   $0F2E gg1-7.s:1656  .db 0xFA
