// Copyright 2026 by Moshix
/**
 * GENERATED FILE -- do not edit by hand.
 * Run `node tools/gen-sound.mjs` to regenerate.
 *
 * 54xx.bin from the Galaga ROM set: the MB8844 program of the Namco 54XX
 * explosion/noise chip, run by src/machine/namco54.js. Namco's code.
 */

const B64 =
  'xsZSEj0GWICQGwrKG3G4yT4EWYQNHBgNHBoNHBoNHBoNHB0cgy9xCAoNgDj4IwGIIAgNIQ4aaEGI'
  + 'IiOQAYkNDhoNf2iQWBlokFmGGWiQCBlokAgZDbHY37L/kIUdkuZbgQ1ZhR2RIwwEWw2w9VAIDbD4'
  + 'iFnTUAgNWYcaUB1okIUNf2iQDSMcIw4cHZGIHWhmiVmTD7HYjgmKDY443pAhATjliSDniSKNDX9o'
  + '/FgZaPxZixlo/AgZaPwIGQ2xaMDJsmjskIodkmjQW4kNWYodkSMMeARbDbBo41AIDbBo5lmNaLpQ'
  + 'CA1ZjBpQHfyKDX/8DSMcIw4cHZGNHWjQWo8NizvDkIEDiA2KIw4diQ2LDh1ZgDjhWoYNI4oOHYcN'
  + 'iw4dWY8Nf2gSWowZaBIIGWgSCBloEo9ZGQ2waUdaDRwjDhwdf2gSkVkdWoQNjR1/14UNjh2MkB1o'
  + 'EoUNjh2w448dWR1oEpCMHWgSG1NUgBNajx1UUxtSPgQ8AAAAAAAAAAAA/AAAAGnAAABp3AAAalUA'
  + 'AGpdAABp+QAAakAAAGloAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAD8AAAAUj4EPBtTVFuADVmF'
  + 'HYiTHVuHDVkaWw1ZHVRTG1I+BDwbU1RbiA1Zih2NkwpbDVEIDVmMGlEdUxtSVD4EPBtTVFqBDYwd'
  + 'gg2NHYMNjh2ADY8dklkdUxtSVD4EPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAG1NUWolVPwQly8gly4ATVRoSGlXlG1NUh1U/BOUbU1tUj1U/BCXo5SXogBNVGhIaFFUj'
  + 'DL7lUxtSVD4EPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  + 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';

/** @param {string} s @returns {Uint8Array} */
function decode(s) {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i += 1) out[i] = bin.charCodeAt(i);
  return out;
}

/** The 1 KB 54XX program. @type {Uint8Array} */
export const MCU54_ROM = decode(B64);
