// Copyright 2026 by Moshix
/**
 * GENERATED FILE -- do not edit by hand.
 * Run `node tools/gen-graphics.mjs` to regenerate.
 *
 * Decoded from the MAME `galaga` ROM set (galaga.rom) using MAME's gfx
 * layouts and palette math. The artwork is Namco's, from the 1981 board.
 *
 * Pixels are 2 bits (pen 0-3), packed four per byte and base64 encoded.
 * Bitmaps are in RASTER orientation (the monitor's native landscape scan, as
 * MAME holds them), NOT rotated for the player: the renderer rotates the
 * whole finished frame once. See tools/gen-graphics.mjs.
 */

/**
 * Number of 16x16 sprites: 8 KB / 64 bytes. 0-63 come from gg1_11.4d, 64-127
 * from gg1_10.4f. Double-size sprites use four consecutive codes.
 */
export const SPRITE_COUNT = 128;
export const SPRITE_SIZE = 16;

const PACKED =
  'A8AAMA/FFDw/9Rc///f3P/P//zPD3/0wgV+9EMF+7xDA/M8AQPBDAEDwQwAA8AMAAPADAADAAAAAwAAAAMAAAMAAAADAAAAA'
  +   '8FMMAPBTX8Awf1/wEPzfPwB+/z8Ae/0MAHO/BADxPwAA8DMAAPwQAAD8AAAAMAAAADAAAAAwAAAADAAAAA8AAAAPAABATzEA'
  +   'EH8/AAD8fwAA/F/AAN///0Be/z8A/P8EAP87AQD/BAAADwAAwAMAAMAAAAAAAAAAAMAAAADwAAAA/AAAAPEFA0DwxwAA/D8A'
  +   'APt/AUBw/wEAcP3/APz/PwA/OAwADwwBwABBADAAAAAAAAAAAAAAAAAADwAAwAMAANADAADEAwAA8BcAAPz3AwD5/wAA/P8B'
  +   'AH9/AQB//QDA////8I/DPzxAAAEAAEAAAAAAAAAAAAAAAMADAAD8AABAPwAAADwAAIB/AQD9XwEA8P8PAPz9A8B/dQX///8F'
  +   'wAP+AADQyw8AAAD/AADQDwAAAAAAAAAAAAAAAAAA9f8AAAA/AADADwDU+wMAAP4XAMD/FcD/1w////X/wP/XDwDA/xUAAP4X'
  +   'ANT7AwAAwA8AAAA/AAD1/wAAAAAAAPX/AAAAPwAAwA8A1PsDAAD+FwDA/xXA/9cP///1/8D/1w8AwP8VAAD+FwDU+wMAAMAP'
  +   'AAAAPwAA9f+gAAAoqAIAqlgCAJZYAgCWmAIAmmhCBKZgSoQmoPq/Kqj6v6qA+r8KAPi+AACgKgAAWJYAAFqWAgCACAAAgAgA'
  +   'AAACAACgIgAAqIAAgCqAAoACAAqgQoQKqHIECqD6DwqA/j8KgP6vCgC4ryKApqoAoGUBAABoCQAAgCAAAAAAAAAIAAAAKgAA'
  +   'gCoAAIAlAACACQAAgAkAKqgKACqgHoElgP6BJgD/qwqA/qsCaPqqAEAmqACAlgAAAIIAAAAAAAAAAAAAAIAqAICgqgKAqgII'
  +   'ACoACIDKBSiA+hMoAP4fKij+PypA6Y8KQOmrAoCUqgIAFigKAIAAAACAAAAAAAAAAAAAAACAKgAAYCkAAKgpAICqAgCAKgAA'
  +   'gCoAAAB+AQAo/wAAkP8BKlD+q6moulopYImqCgACCgAAAggAAAAAAAAAAAAACAAAAKCqAACoqgIAKiAKCOoAICD+FwBQ/gOg'
  +   'WPoXKKD+Dypg+QIKQKKqAoCiqgKAACoAAAAIAAAAAAAAgKAqAIBqpQCglqUgoKoqoKgKAFD+AwBa/hcAoPoDAFr+FwBQ/gMA'
  +   'oKgKACCgqioAoJalAIBqpQCAoCoAAAAAAIAAAACAAgAAoKoAIKiqAqCogApQ/gMoWP4XoKD6AwBY/hegUP4DKKCogAogqKoC'
  +   'AKCqAACAAgAAgAAAAAAAAAAAAAAAAAAAAAAAAAAMwADAj8oP8H/1P8C/+g8Av/oDwH/1D/BTFT/w0x0/8IMIPwCDCAMAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAPAAAADwIAAL/KAwC/+gMAXPUAwF/9AMCoDgAwrfoAMNjBADCAMAAAADAAAAAwAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAwAAAAP8gAAD/KQDA/yUD/L/WP/x8+g/8VP0/MFz9AwDIwQMAgvADACD8AwAAzAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AMADAADwAwAA8KgAAMOlAMC/lgDwkBoPMFX6DwBczQMAcgwAAEg8AAAADwAAwAMAAAAAAAAAAAAAAAAAAMAMAADADwDA/z8A'
  +   '8P8PAMDzpwLw8JYAAFRaAABe+Q+AUP8DAHj/AwAC/AMAwD8AAPAPAADADwAAAAAAAAAAAAAAAAAAAAAAAADwAAA8/wDwMz8A'
  +   'AOCnAACkpQIArqUAAKT1AAC4/w8AEPMPAMADAAA/AAAAAAAAAAAAAAAAAAAAPzAAAP/8AMD//wAAwP8DANQ/AIBemgAAVJoA'
  +   'gF6aAADUPwAAwP8DwP//AAD//AAAPzAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//wDAMD8AwDUPwAAXpoAAFSaAgBemgAA1D8A'
  +   'AMD8A8D//AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAIBKqBCBSqgyo8qgEqFCgBqpQIA6K8AAPA/AABYlwAAcjcC'
  +   'gAADCAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAoBAAAKBUKACg/CgBoFQoAaIUCAPCvAAD6rwCA3AUAANAtAADAgAAAAIAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAKAACAKgAAgAoAAAAqBQAAyhcAAGoPKABahSqA/KkqKPWrCgD3CwAAXAIAAMwIAAAACAAAAAAA'
  +   'AAAAAAAAAgAAgAoAAKACAACgRgAA4B8AAGh9CID+tSog97cKAPWrAgBcCwAA0wIAAAACAACAAAAAAAAAAAAAAAAAAAAAoAIA'
  +   'AKgCAACoAAAAqAAAACgEAChqFwCAXx8AcH8NAEB/IgLwtaoKAIeqCgAggAIACAAAAAgAAAAAAAAAAAAAAAAAAAAAqAAAAKoA'
  +   'oKACAACidAAA93UBAPV1AMD/BQAA9aoKACyqCgAgAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAoAKAAKgCAAKqAgCIKgAAtwIA'
  +   'APV1AMD/dQEA9XUAALcCAACIKgAAAqoCgACoAgAAoAIAAAAAAAAAAAAAAAAAAAAAAAAAAIACqAIAiKoCALcCAAD1dQDA/3UB'
  +   'APV1AAC3AgAAiKoCgAKoAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAwAAAATAABAwAAAPLwA8DACABwDAAATDwDAgCMA'
  +   'wAEAABABAKjADwAAAAMAgAAMgKoAA6qqAAAAAAAAAAAP8AAAEAUDAMPADADAFBAAAIDCAAAAzACqquABACrgAYAKQAeqAkAH'
  +   'qCowA6oqDAOqCsAAqqogAAADgKrABACAwAQAAAADAKgAIwAAAAwPAACMUAAA8MIBAAAfjAAA8AwAAADQAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAACqCgwAqioMAKgqQACqAgADgAogAwAqzACqqswAAMAxAAAgAQAf/wAAEPQAAB80AAAQBAAAwAMAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAwADAD8ADwA8ADMAQAQwAAAE/ADwBQ/P8ADDz8AAzP8wDCvz/AwO8XAMBfRQD8HEUA/19AwPNPVAAAAAAAAAAA'
  +   'AAAADAACAAwAMAAD/ANAAP8zMQDPPAUAM/8AAH/BAAOVPT8MVNX/AFTk8wAQ1TwACPU/ABXwDwDAy1xhwPNXRADPHwHALx80'
  +   'wE9fFQD/UxQA8DzFAAD//wAIPP8AMPA8AM/wwwDDwP/AAAg/MAAwADAAMAAAAAAABvXzABHV/wxA5Dw8EdTzDFXw8zxF9TzA'
  +   '1f8PABr8AwD/M/AA8w8EAPwPIwD/A4MAPzAMAwAMAAwAAAAAAAAAAAMAMD+MAP//MMLP8DDAMcUA/1UV8A/1V3xRVFVfVFVQ'
  +   'H5UfRU91Vlc/XUVVTFUVFD9VVwB/VFUEfxVAUf9tFUAAMgDAwDBAMPMPQAgPwA8B/8M/CPzz9wCV/fUAVgX0AFVF8QDVVTUA'
  +   'UVX2PFBB1f9BUEX1ARRV9VJEVfQVVFU9/+VVVMDVRUD805ER/9RVBD91FQE8VUXQfFRVVHzZV/3wV31VwBNV1gBwVH3AcFEU'
  +   'wMIH9fAA/z8MAPwDAAAAAAVAUTMBVEYDUVRFAwaR0Q8RUNUPUFHBA1EVPABVTf8A1VX/AHVVDwBZUQ8DF/+DA/zzAAv/AAg4'
  +   'AAAw8AAAAMAAAAAAAAAAABAAEAHQAFACwAEQCABBAAAASsAFAFB89QAEFFQABE1RAENVFcBArRUAQFdFANQURQD1VUDA8UVk'
  +   'AAAAAAAAAAAAAAAEAAIABAAwAAL8AcAAVTMRAE0UBQARdQAAVUEAA1UWPQxUVdUAVFRRABBVNAAEVTUAFVAFAEDFVFGAkVVE'
  +   'AE0VAUAXGRRAR1UVAFVRFABQFEUAAFVVAAQcVQAQUBQARVBBAEFAtYAABB8wADAAMAAwAAAAAAAFlVEAIXVdBEB0PBQRVHEE'
  +   'VVBxFEVVFEBVVQ8AFdQDAFUxUABRBQQAdA8RAFYBQQA/EAQCAAQACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAACgAAAA6lUAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAQAAAABAAAoAMA'
  +   'AOACAACgAgAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAA6lUA'
  +   'AKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAKgAAAC4AAAAEAAAABAAAAAQAAAAEAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAA/A8AAA8wAAADPAAA/A8AAAAAAADDDwAAMzAAADMwAAAzMAAAPwwAAAAAAAAAMAAA/z8A'
  +   'AAwwAAAAAAAAAAAAAFQFAAABEAAAARAAAFQFAAAAAAAAVAUAAAEQAAABEAAAVAUAAAAAAAAAAQAAVRUAAAQBAAAQAQAAQAEA'
  +   'AAAAAABUBQAAARAAAAEQAABUBQAAAAAAAFQFAAABEAAAARAAAFQFAAAAAAAAQQUAABEQAAAREAAAERAAABUEAAAAAAAAVAUA'
  +   'AAEQAAABEAAAVAUAAAAAAABUBQAAARAAAAEQAABUBQAAAAAAABQFAABBEAAAQRAAAEEQAAAUBQAAqAoAAAIgAAACIAAAqAoA'
  +   'AAAAAACoCgAAAiAAAAIgAACoCgAAAAAAAKgKAAACIAAAAiAAAKgKAAAAAAAAqioAAPwPAAADMAAAAzAAAPwPAAAAAAAA/A8A'
  +   'AAMwAAADMAAA/A8AAAAAAADDDwAAMzAAADMwAAA/DAAAAAAAAP8/AABUBQAAARAAAAEQAABUBQAAAAAAAFQFAAABEAAAARAA'
  +   'AFQFAAAAAAAAAQUAAEEQAABEEAAAUAUAAAAAAABVFQAAAAAAAAAAAABVVYUAAJWFAIC/gIC8v4CQlb+PlZW/v7WflYWVlb+/'
  +   'kJW/j4C8v4AAgL+AAACVhQBVVYUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAoAAAIgAAACIAAAqAoAAAAAAACoCgAAAiAA'
  +   'AAIgAACoCgAAAAAAAKgKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwPAAADMAAAAzAAAPwPAAAAAAAA/A8AAAMwAAADMAAA/A8A'
  +   'AAAAAAD8DwAAAiAAAAIgAACoCgAAAAAAACggAACCIAAAAiIAAAIoAAAoIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAMwAAADMAAA/A8AAAAAAAADDwAAzzAAADMwAAADMAAAAwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPADADD8DwAw'
  +   'DzD/PwMw/z8DPAww/A8AMPADAAAAAAAAPDADD/8wzz/zM/8wwzPzMMM/wzAPPwM8DDwADAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAMAMAwMAwAADcDQAAdA0AANwDAAADDAAAMAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIAAAACjAIAyDAAAUDAD'
  +   'DHPRAMBEFgwAp7cDwGClAjBspgaAQowAgAzAAAAwBAAAAAAAAAAAAATAMCAAA4ACMKwwAEAAQwEMU0ABoQAwwCAMAwoMAwAA'
  +   'ADDMoJsKACBAAMRrUDAkCAwMCmwAgDAAwBAAAwMQDEAAAAAAAAAAAAAAwAAAAAAAAAAABAAAADAAAQwDAAAAAAAAwAAABAQK'
  +   'ADAAQgDAIDAAA8AAAAwAAAAAIxAAMCAAAAAAAAAAAAAAAAAAAAAAAAQAAAAyCAAAAggAAAADAwADwAAAwBAAADAAKAAwCgAM'
  +   'AAADAACAQAAABAAAAAwMAAAAMAAAAgUAAAIAAAAAAMAAwCgAEAAgAAAwAAwAADAUAAACgAAAAgAAAAAwAAAABAAADAAAAAAA'
  +   'AAAAAAAAAAAAAAMAMDAAAADEwAAAoAAAAAAwAAADAAADDAAAAEAAABICAwAACAAAAAAAAAwAAQAAAAAAAAAAAAAAAAAAAAAA'
  +   'ACAABAwAAAAAAAAAwAAAAAAACAAAAAAAAAAAAADAAMAAAAAADABAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAQAAAAAAAAAACAAC'
  +   'AwCAAAoAAAAAAAAwAAAAAAAAQAAAwAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAwAAAAAAAAwAAAAAA'
  +   'KAAAAAAAAAgADAAAAAQAAAAAAAEAAAAAAAAAAIAAAAAwAAMAAAAAgAAAAIAAAAAAAAAAAAAAAgAAAMAAAAAAAAAAAAAAADAA'
  +   'AAAAAgAAAAAAAAAAAAMwAAEAAAAAAAAAAAAAIAAAAIEAMAAAAAAAAAAAAAAAQAQAAEAFAEBVFQBQVQUAQFGtAlBQvgAA/PoA'
  +   'APZbBYDwVQEA2FUBAAJUAQBAFQAAUAUAAEAFAAAAAABVVQVQBQAFUAUABVBVVVVVVVVUFQUAAAAFAAAAVVVUVQVQAABVVQAA'
  +   'VBVUFQAAVVUAAAVQBVAFUAVQBVAFUAVQQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAQEAAAEBAAEBAQEBA'
  +   'QEBAQEBAQEBAQEBAAEBAQEBAAABAQAAAQEAAAEBAAEBAQABAAEBAQAAAQEAAAEBAQEAAAEBAAABAQAAAAEAAAABAAAAAAAAA'
  +   'AAAAQAAAQEAAAAAAAAAAAADAAAAAwAAAAMgIAADKKACAzqwAoP+/AuB//wLgddcCIFQFAiBQAQIAQAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAwAAAAMAAAgDwAAKIMAgPqzAoD//wKA//0KoNT9CyBQ1QoAUAUCAEAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AADAAACA8gAAqjAAgP4MAoD/zwKg/P0CIPT9AgBU/woAUPUCAFCAAgAAgAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqgoD'
  +   'gP7DAKD/MwAg/A8CAPT9AgB0/wIA1P8CAFT9AgAAsAIAAKAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAIAAAAKoqAID+Dw8g/MMD'
  +   'APQ/AAB0DQIA1b8CANW/AABQvwAAAKwAAAAqAACAAgAAAAAAAAAAAAAAAAAAAAAAAKgAAIC6CgAA/CsAAPQPAAD1ww8AVf8A'
  +   'QPUPAADVrwAA0CsAAMALAACgCgAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqgIAAPAKAADQKwAA1K8AAPUDAEBV/w8A9QMA'
  +   'ANSvAADQKwAA8AoAAKoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAADAMAAAwMAAAPADAADwAwAA9RcAQPFTAEDxUwBQwVABECESAQAgAgAAAAAA'
  +   'AAAAAAAAAAAAAAAAADwAAADDAAAAAAMAAAADAADAAwAAwA8AQPUPAFDxFwBU8FMARDBQAACIVAAAiEQAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAA8AMAAA8MQNU/DFDBDwBE8QcAQPATAAA4FAAAIhQAACAVAAAAEQAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAA/AAAAwAAAAMAAABU/AFDFPwBA8T8AQPAPAAD4EwAAIhQAAAgVAABABQAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAFAV/ANART8MUPA/DADwDwCA/gQAAAgEAABCBQAAUAUAAAABAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAVAAMAVQAM'
  +   'QEEPDADw/wOA8j8AAPwDAIACAQAAQAEAAFQBAABQAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAVAAAAFUBAAAAAQCA8j8A'
  +   'APz/A4DyPwwAAAEMAFUBAwBUwAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAEEAAARBAAAFQUEEBUFVVAUClVgBAlVUAAJc1AABfPQAAfA8A'
  +   'AEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAABAEAAAQBAAQEAQEUFBEBVBQVApVYFAJdVAQCXVQAAXz0AAN8PAAAQAAAAEAAA'
  +   'AAAAAAAAAAAAAAAAAAQAAAAEEAAABRAAAAUEAABVBQAAVQUQAJcWBcCXVQUAZ1UBAFcdAAD0DwAAwQAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAEAAAAAQAAAAVQAAAFRAAAFUFAMBnBQDAlQUAwGVWBMBXVQEAXVcAQPwDAAAAAAAAAAAAAAAAAAAAAAAAAAQA'
  +   'AEABAABQAQAAUAAAAFQBBQBfVQAAVxYAwJcWAABnFQAAVVUVQPxXAQDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAQAUA'
  +   'AFABAABcAQAAXxUAAFdWBQCnFgBQVQYAAF8VAAD/VQAAAFUFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAQBAFQAAfAUA'
  +   'AF8FAABXFgBQpVYFAFcWAABfBQAAfAUAAEAVAAAAVAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAIAAAACAAAAAgAAAQIVUAFSVVQWoqqoK'
  +   'qoqoKgCAAAAAsAMAADwPAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAAgAAAAIAUBUCAKiVEACqqlUAgIpaBQCAqAYALIAK'
  +   'AM8ACADAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAACAAEAEIAFAFCgCqFQIAoJoAAACqFQAAoFYAACNqAcA7qAEAMKAC'
  +   'ADAAAgAAAAAAAAAAAAAAAAAAAAAAAAACUACAAGoFIACoFQgAoBYCAACaAAAAYAUAwIgVAPCCFgAAD1oAAANqAAAAKAAAACAA'
  +   'AAAAAAAAAAAAAAAAaAEAAKAFAAKgFoAAgBYoAAAaCgAAqAAA/GoBAICgBQDAoxUAwIAGAACAFgAAAAIAAAACAAAAAAAAAAAA'
  +   'gBYAAAAaAAAAWgAAAFgBAABoAAowYKgA8KgCAACCBQDAowUAwKAFAACgBgAAgAYAAIACAACAAAAAAAAAAAgAAABoAAAAaAAA'
  +   'AGgBAABoAQAwaAEA8GAAAICqqgrwYAAAMGgBAABoAQAAaAEAAGgAAABoAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw/A8P'
  +   'PAzAMDD8wzAwAMwwMADMMDAMzDD88AMPAAAAAAAAAAAAAAAAAAAAAAAADAAAAA8AAAAPAFDAD/BgxQP/gFXxPwBW/T8Aav0D'
  +   'wKsdAPDvFwD88ysADPCAAAD8ACIA/AAIADwAIgAMAIAAAAwAAAAPAAAADwBQwA8AYNUPALxVBQD8Wv0PwGv9/wCg/v8A/PY/'
  +   'APwoAAD/gAAAPwAiAD8ACAAPACIAAwCAAAAwAAAA/ADAA/8AUM8/AGDVDwCAVgMAAKoFAACoDwAA7z8AwM//AMAP/wPwA/wD'
  +   '8ADwIzAAAAgAAAAiAAAAgAAADAAAAA8AAAAPAFDAD/BgxQP/gFXxPwBW/T8Aav0DwKsdAPDvFwD88ysADPCAAAD8ACIA/AAI'
  +   'ADwAIgAMAIAAAAwAAAAPAAAADwBQwA8AYNUPALxVBQD8Wv0PwGv9/wCg/v8A/PY/APwoAAD/gAAAPwAiAD8ACAAPACIAAwCA'
  +   'AAAwAAAA/ADAA/8AUM8/AGDVDwCAVgMAAKoFAACoDwAA7z8AwM//AMAP/wPwA/wD8ADwIzAAAAgAAAAiAAAAgAAADAAAAA8A'
  +   'AAAPAFDAD/BgxQP/gFXxPwBW/T8Aav0DwKsdAPDvFwD88ysADPCAAAD8ACIA/AAIADwAIgAMAIAAAAAAAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJABAACQAQAorA4KKK8+Cujv/gro4/IK'
  +   '6MDACijoCgooqioKhOqqBID6qwCAfq8AgPqrAIBqqgAAaioAAGgKAAAAGQCgABkAoLAKAKC/Oiigv/so6KD7KCjA8Csk6sIK'
  +   'gKoKCqD6Kgqg/yoEoN8rAKD+KgCgmioAgKYKAACkAgAAChAAgAqQAYD+awCg/qoAoP/uAKiA7yMEKsuroOrCK6CqyiqovwoK'
  +   '6v+KAqj3KgKo7UoAqKkKAECqAgAAKgAAAKAAAACoAAAAKgAJgPpPBqD+qwGkDKoAAACuA6Aq6wOo6sCj6rvCq+qv8irqvYIK'
  +   '6r+iApqqogCkqhAAoCoAAAAACAAAgCoAAKAKAACqPxBAyP8mAAKgWqCq+Aqoqr4O6K/jD6q/yg/qvcqvWr/KqqSuoiqgqqIC'
  +   'oCokAAAIAAAAAAAAAACoAgCkqgIAoA4AAAD/AKAq/FOoqqCqqqvyWuq/rwraveIP5a/CA6ivwgOoqrAqoCqqKgAAKQAAAAAA'
  +   'AAAAAAAAAAAAkKoKAICqCqAq/ACoqvADqqvCD+qvolrVvf+q6q+iWqqrwg+oqvADoCr8AACAqgoAkKoKAAAAAAAAAAAAAAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

/**
 * All sprites as one flat array of 2-bit pens in raster orientation: pixel
 * (x, y) of sprite n is at `n * 256 + y * 16 + x` (same axes as TILE_PIXELS).
 * @type {Uint8Array}
 */
export const SPRITE_PIXELS = unpack(PACKED, SPRITE_COUNT * 256);

/** @param {string} b64 @param {number} length @returns {Uint8Array} */
function unpack(b64, length) {
  const binary = typeof atob === 'function'
    ? atob(b64)
    : Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i += 1) {
    out[i] = (binary.charCodeAt(i >> 2) >> ((i & 3) * 2)) & 3;
  }
  return out;
}
