// Copyright 2026 by Moshix
/**
 * GENERATED FILE -- do not edit by hand.
 * Run `node tools/gen-graphics.mjs` to regenerate.
 *
 * Decoded from the MAME `galaga` ROM set (galaga.rom) using MAME's gfx
 * layouts and palette math. The artwork is Namco's, from the 1981 board.
 *
 * Pixels are 2 bits (pen 0-3), packed four per byte and base64 encoded.
 * Bitmaps are in RASTER orientation (the monitor's native landscape scan, as
 * MAME holds them), NOT rotated for the player: the renderer rotates the
 * whole finished frame once. See tools/gen-graphics.mjs.
 */

/**
 * Number of 8x8 characters. charlayout_2bpp is RGN_FRAC(1,1) over the 4 KB
 * ROM, i.e. 256: codes 0x00-0x7F are the normal set and 0x80-0xFF the same
 * glyphs mirrored in raster X, which the hardware selects instead of
 * flipping pixels when the screen is flipped (see get_tile_info in MAME's
 * galaga_v.cpp). Video RAM only ever supplies 7 bits of code.
 */
export const TILE_COUNT = 256;
export const TILE_SIZE = 8;

const PACKED =
  '8AP8Dw8wAzADPPwP8AMAAAAwADD/P/8/DDAAMAAAAAA8MP8w8zPDM8M/Dz8MPAAAAw/PP/8w8zDDMAM8AAwAAAAD/z//Pw8D'
  +   'PAPwA8ADAADAD/M/MzAzMDMwPzw/DAAAAA/DP8MwwzDPMPw/8A8AAA8APwDzAMM/Az8PAA8AAAAADzw/wzPDM/Mw/zA8DwAA'
  +   '/AP/D8M8wzDDMP8wPAAAAPA//D8PAwMDDwP8P/A/AAA8D/8/wzDDMMMw/z//PwAADAwPPAMwAzAPPPwP8AMAAPAD/A8PPAMw'
  +   'AzD/P/8/AAADMMMwwzDDMP8//z8AAAAAAwDDAMMAwwDDAP8//z8AAMM/wz/DMAMwDzz8D/ADAAD/P/8/wADAAMAA/z//PwAA'
  +   'AzADMP8//z8DMAMwAAAAAP8P/z8AMAAwADAAPAAMAAADMA88PD/wD8AD/z//PwAAADAAMAAwADD/P/8/AAAAAP8//z/8APAD'
  +   '/AD/P/8/AAD/P/8/wA/wA/wA/z//PwAA/A//PwMwAzADMP8//A8AAPwA/wMDAwMDAwP/P/8/AAD8M/8PAz8DMwMw/z/8DwAA'
  +   '/DD/PMM/Aw8DA/8//z8AAAAPzD/PMMMwwzD/PDwMAAADAAMA/z//PwMAAwAAAAAA/w//PwAwADAAMP8//w8AAP8A/wPADwA/'
  +   'wA//A/8AAAD/P/8/wA/wA8AP/z//PwAADzw/P/wP8AP8Dz8/DzwAAD8A/wDAP8A//wA/AAAAAAAPMD8w/zDzM8M/Az8DPAAA'
  +   'AAAAAAAAAAAAAAAAAAAAAP/////////////////////AAMAAwADAAMAAwADAAMAAAwADAAMAAwADAAMAAwD/////AwADAAMA'
  +   'AwADAAMAAwADDAwzMAzAAAwDMwwMMAAAAAAAAAAAAAAAPAA8AAAAAADAAMAAwADAAMAAwADA//8AAAAADwA/AP8A8PMAAAAA'
  +   '//8AwADAAMAAwADAAMAAwPAPDDADwDPMM8zDwwww8A8FAAUABQAFAFVVVVUAAAAARVFFUUVVQFUAAAAAVFVVVVVVAAAAAFRV'
  +   'VVVVVUVRRVFVVQUABQBVVVVVBQAFAFVVBVAFUAVQVVVUFQAAAABUVQVQVVVUFQAAAAAFUAVQBVAAAAAAVBVVVQVQBVAFUAVQ'
  +   'AAAA6wDrAOsA6wDrAOsA6wAA+gN6D/o9+vf6PXoP+gMAALCqsPuw+7C7sL+wv7CqAAD6A/sN+zf73/s3+w36A3BV8H3wX/BX'
  +   '8Hfw9/D/AABV/f0/VQ/3A/8APwAPAAAAAAAAAPD/8Pfwd/BX8F/wfQAAAAAPAD8A/wD3A1UP/T9WVZqWqqVqqWqpqmWqVqqq'
  +   'mamaKVoJlgKlACkACgACAAAAqqqqVqplaqlqqaqlmpYAAAIACgApAKUAlgJaCZop/f/9/1XPVf/V8/X/1f9VVf9V/BXXB1UB'
  +   'VwAVAA8AAQAAAFVV1f/1/9Xzdf91z83/AAABAA8AFQBXAFUB1wf8FX/ff9+vqq+qr6qvqn/ff9+r/qo/6g/6A/4APwAPAAMA'
  +   'AAB/33/fr6qvqq+qr6p/3wAAAwAPAD8A/gD6A+oPqj/8v8D/AMAAAADoAAAAgAAAAAAAAACAAAAA6AAAAMDA//4/+gO/Cv0K'
  +   '9wPAD/4/AAAAAAAA/j/AD/cD/Qq/CvoDAAwAAAAAAAAAAAAAAAAAAACBAIFAgEAgFQgAyIDCKjAqMIDCAMgVCEAgQIAAgQCB'
  +   'AAAAAAAAAAAAAAAAAAAADATIAMIAMAAAAAAAAAAAAAAMgQyBDIFDgEOAQCAQIBAIEAgQIEAgQ4BDgAyBDIEMgQAAAAAAAAAA'
  +   'AAAAMADCBMgQyBDIBMgAMgAAAAAAAAAADIEMgQyBDIEMgUwgQyBDIEMgQyBMIAyBDIEMgQyBDIEAAAAAAAAAAAAyBMgQyBDI'
  +   'QCAQIBDIEMgEwgAwAAAAAAyBDIEMgQyBDIEMgUMgQyBDIEMgDIEMgQyBDIEMgQyBAAAAAAAwBMIQyBDIECBAIEMgQyBAIBAI'
  +   'EAgECAACAAAMgQyBDIEMgQyBDIEDgUMgQyADgQyBDIEMgQyBDIEMgQAAAAIECBAIEAhAIEMgQyAAwgAAAAAAAAAAAAAAAAAA'
  +   'QyBDIEMgQyATCBMIEwgHCAyBDIEMgQyBDIEMgQyBDCEMIQyBDIEMgQyBDIEMgQyBBwgTCBMIEwhDIEMgQyBDIAAAAAAAAAAA'
  +   'AAAAAAAAAMIEwgTCAAAAAAAAAAAAAAAAQyBDIEMgEwgTCBMIEwgHAgyBDIEMgQyBDIEMIQwhDCEMIQwhDCEMgQyBDIEMgQyB'
  +   'BwITCBMIEwgTCEMgQyBDIAAAAAAAAAAAAAAAAATCBMIEyATCBDIAMgAAAAAAAAAAQyBDIEMgQyATIBMIEwgTCAyBDIEMgQyB'
  +   'DIEMgQyBA4EDgQyBDIEMgQyBDIEMgQyBEwgTCBMIEyBDIEMgQyBDIAAAAAAAAAAAADIEMgTCBMgQyBDIEMIEMgQyADAAAAAA'
  +   'QyBDIEMgQyBDIEMIEwgTCAyBDIEMgQyBDIEMgQyBDIEMgQyBDIEMgQyBDIEMgQyBEwgTCEMIQyBDIEMgQyBDIAAAAAAAMAQy'
  +   'BDIQwhDIEMgQCBAIBAgECAQCBAIAAgAAQyBDIEMgQyBDIBMgEyATIAyBDIEMgQyBDIEMgQyBDIEMgQyBDIEMgQyBDIEMgQyB'
  +   'EyATIBMgQyBDIEMgQyBDIAAAAAIEAgQCBAgECBAIEAjAD/A/DPAMwDzA8D/ADwAADAAMAPz//P8MMAwAAAAAAAw8DP/Mz8zD'
  +   '/MP88DwwAADwwPzzDP8MzwzDPMAwAAAAwAD8//z/wPDAPMAPwAMAAPAD/M8MzAzMDMw8/DD8AADwAPzDDMMMwwzz/D/wDwAA'
  +   'APAA/ADP/MP8wADwAPAAAPAA/DzMw8zDDM8M//A8AADAP/D/PMMMwwzDDP8APAAA/A/8P8DwwMDA8Pw//A8AAPA8/P8MwwzD'
  +   'DMP8//z/AAAwMDzwDMAMwDzw8D/ADwAAwA/wPzzwDMAMwPz//P8AAAzADMMMwwzD/P/8/wAAAAAAwADDAMMAwwDD/P/8/wAA'
  +   '/MP8wwzDDMA88PA/wA8AAPz//P8AAwADAAP8//z/AAAMwAzA/P/8/wzADMAAAAAA8P/8/wwADAAMADwAMAAAAAzAPPD8PPAP'
  +   'wAP8//z/AAAMAAwADAAMAPz//P8AAAAA/P/8/wA/wA8AP/z//P8AAPz//P/wA8APAD/8//z/AADwP/z/DMAMwAzA/P/wPwAA'
  +   'AD/A/8DAwMDAwPz//P8AAMw/8P/8wMzADMD8//A/AAAMPzz//MPwwMDA/P/8/wAA8AD8MwzzDMMMwzz/MDwAAADAAMD8//z/'
  +   'AMAAwAAAAADw//z/DAAMAAwA/P/w/wAAAP/A//AD/ADwA8D/AP8AAPz//P/wA8AP8AP8//z/AAA88Pz88D/AD/A//Pw88AAA'
  +   'APwA//wD/AMA/wD8AAAAAAzwDPwM/8zP/MP8wDzAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////wADAAMAAwAD'
  +   'AAMAAwADAAMAwADAAMAAwADAAMAAwP////8AwADAAMAAwADAAMAAwDDAzDAwDAADwDAwzAwwAAAAAAAAAAAAADwAPAAAAAAA'
  +   'AwADAAMAAwADAAMAAwD//wAAAAAA8AD8AP/PDwAAAAD//wMAAwADAAMAAwADAAMA8A8MMAPAM8wzzMPDDDDwDwBQAFAAUABQ'
  +   'VVVVVQAAAABFUUVRVVFVAQAAAABVFVVVVVUAAAAAVRVVVVVVRVFFUVVVAFAAUFVVVVUAUABQVVUFUAVQBVBVVVQVAAAAAFUV'
  +   'BVBVVVQVAAAAAAVQBVAFUAAAAABUFVVVBVAFUAVQBVAAAOsA6wDrAOsA6wDrAOsAAADAr/CtfK/fr3yv8K3ArwAAqg7vDu8O'
  +   '7g7+Dv4Oqg4AAMCvcO/c7/fv3O9w78CvVQ19D/UP1Q/dD98P/w8AAH9V/H/wVcDfAP8A/ADwAAAAAAAA/w/fD90P1Q/1D30P'
  +   'AAAAAADwAPwA/8Df8FX8f1WVlqZaqmqpaqlZqpWqqqpqZmimYKWAlgBaAGgAoACAAACqqpWqWapqqWqpWqqWpgAAAIAAoABo'
  +   'AFqAlmClaKb/f/9/81X/Vc9X/1//V1VVVf9UP9DXQFUA1QBUAPAAQAAAVVX/V/9fz1f/XfNd/3MAAABAAPAAVADVQFXQ11Q/'
  +   '9/33/ar6qvqq+qr69/33/b/q/Krwq8CvAL8A/ADwAMAAAPf99/2q+qr6qvqq+vf9AAAAwADwAPwAv8Cv8Kv8qv4//wMDAAAA'
  +   'KwAAAAIAAAAAAAAAAgAAACsAAAADAP8D/L/Ar6D+oH/A3/AD/L8AAAAAAAD8v/ADwN+gf6D+wK8wAAAAAAAAAAAAAAAAAAAA'
  +   'QgBCAAIBCAEgVCMAgwIMqAyogwIjACBUCAECAUIAQgAAAAAAAAAAAAAAAAAAADAAIxCDAAwAAAAAAAAAAAAAAEIwQjBCMALB'
  +   'AsEIAQgEIAQgBAgECAECwQLBQjBCMEIwAAAAAAAAAAAAAAwAgwAjECMEIwQjEIwAAAAAAAAAAABCMEIwQjBCMEIwCDEIwQjB'
  +   'CMEIwQgxQjBCMEIwQjBCMAAAAAAAAAAAjAAjECMEIwQIAQgEIwQjBIMQDAAAAAAAQjBCMEIwQjBCMEIwCMEIwQjBCMFCMEIw'
  +   'QjBCMEIwQjAAAAAADACDECMEIwQIBAgBCMEIwQgBIAQgBCAQgAAAAEIwQjBCMEIwQjBCMELACMEIwULAQjBCMEIwQjBCMEIw'
  +   'AACAACAQIAQgBAgBCMEIwYMAAAAAAAAAAAAAAAAAAAAIwQjBCMEIwSDEIMQgxCDQQjBCMEIwQjBCMEIwQjBIMEgwQjBCMEIw'
  +   'QjBCMEIwQjAg0CDEIMQgxAjBCMEIwQjBAAAAAAAAAAAAAAAAAACDAIMQgxAAAAAAAAAAAAAAAAAIwQjBCMEgxCDEIMQgxIDQ'
  +   'QjBCMEIwQjBCMEgwSDBIMEgwSDBIMEIwQjBCMEIwQjCA0CDEIMQgxCDECMEIwQjBAAAAAAAAAAAAAAAAgxCDECMQgxCMEIwA'
  +   'AAAAAAAAAAAIwQjBCMEIwQjEIMQgxCDEQjBCMEIwQjBCMEIwQjBCwELAQjBCMEIwQjBCMEIwQjAgxCDEIMQIxAjBCMEIwQjB'
  +   'AAAAAAAAAACMAIwQgxAjECMEIwSDBIwQjBAMAAAAAAAIwQjBCMEIwQjBIMEgxCDEQjBCMEIwQjBCMEIwQjBCMEIwQjBCMEIw'
  +   'QjBCMEIwQjAgxCDEIMEIwQjBCMEIwQjBAAAAAAwAjBCMEIMEIwQjBCAEIAQgECAQgBCAEIAAAAAIwQjBCMEIwQjBCMQIxAjE'
  +   'QjBCMEIwQjBCMEIwQjBCMEIwQjBCMEIwQjBCMEIwQjAIxAjECMQIwQjBCMEIwQjBAACAAIAQgBAgECAQIAQgBA==';

/**
 * All characters as one flat array of 2-bit pens in raster orientation:
 * pixel (x, y) of character n is at `n * 64 + y * 8 + x`, where x runs along
 * the monitor's scan line (the player's screen Y, downwards) and y across scan
 * lines (the player's screen X, right to left).
 * @type {Uint8Array}
 */
export const TILE_PIXELS = unpack(PACKED, TILE_COUNT * 64);

/** @param {string} b64 @param {number} length @returns {Uint8Array} */
function unpack(b64, length) {
  const binary = typeof atob === 'function'
    ? atob(b64)
    : Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(length);
  for (let i = 0; i < length; i += 1) {
    out[i] = (binary.charCodeAt(i >> 2) >> ((i & 3) * 2)) & 3;
  }
  return out;
}
